### ISSUE TITLE
version6.1.0 : copy then paste, format not good

### ISSUE THREAD

**Issue by singi2016cn** [GitbookIO/feedback#100]
##copy some code,then paste,format bad!
###copy format:
```
{
    "name":"singi",
    "notlike":"version 6.1.0"
}
```
###paste format
```
{ "name":"singi", "notlike":"version 6.1.0" }
```
##may I paste the same as copy?just do as old version,you do! 
###thank you for your working.

**Comment by SamyPesse** [comment]
This is a duplicate of #83.

I'm closing this one, we are working on it.
