### ISSUE TITLE
I how in v6. X Mac using preview effect

### ISSUE THREAD

**Issue by mzkmzk** [GitbookIO/feedback#105]

**Comment by Soreine** [comment]
@mzkmzk I'm not sure to understand what you meant. Could you be more specific?

**Comment by mzkmzk** [comment]
Version is now only one TAB, while writing markdown then directly, according to what I want is like the previous version. There are two tabs, one is my original markdown, the other is a preview.

**Comment by Soreine** [comment]
<img width="455" alt="screen shot 2016-07-21 at 11 40 36" src="https://cloud.githubusercontent.com/assets/5644953/17018433/089d8a06-4f38-11e6-9860-7e3da91a342d.png">

You can use the `aA` button to switch to the preview mode. Does it help ?

**Comment by mzkmzk** [comment]
I'm sorry...I look at the Document Mode icon I thought it was to adjust font size...Never try to click...Thanks
