### ISSUE TITLE
Can not preview the subscript or superscript in markdown

### ISSUE THREAD

**Issue by xmpy** [GitbookIO/feedback#106]
### What is the current behavior?

After input the markdown `2<sup>k1</sup> - 2<sup>k2</sup>`, in the preview of Gitbook editor, I can only see 2k1 - 2k2.

### What is the expected behavior?

See 2<sup>k1</sup> - 2<sup>k2</sup>

#### For GitBook Editor

- Operating System? Windows
- (Desktop) Editor version? 6.1.1
- Was the bug present in previous versions? In 5, it do not has this bug.

**Comment by Soreine** [comment]
Fixed in 6.2.0
