### ISSUE TITLE
Chinese fonts disappear

### ISSUE THREAD

**Issue by dandananddada** [GitbookIO/feedback#112]
**中文字符** will appear as ** when i type enter under markdown editor mode.

**Comment by dandananddada** [comment]
It's really hard to use than v5. I won't editor under preview mode because it's a markdown editor. Otherwise a text editor. It's seems to against the mainly purpose of markdown.

**Comment by youngking** [comment]
same here 6.2.0

**Comment by Soreine** [comment]
Unless I'm mistaken, it is fixed as of 6.2.1
