### ISSUE TITLE
Syntax highlighting makes text disappear

### ISSUE THREAD

**Issue by bovenson** [GitbookIO/feedback#122]
![default](https://cloud.githubusercontent.com/assets/9496690/17141746/ea839960-537f-11e6-8516-6c428a7157a6.PNG)

**Comment by bovenson** [comment]
both windows and linux(ubuntu) has this bug

**Comment by SamyPesse** [comment]
If you are providing any context or method to reproduce the problem, we cannot help you.

Gives us more details about the bug: description and method to reproduce.

BTW: the title of this issue is "unbelievable and unacceptable"

**Comment by AaronO** [comment]
@bovenson Can you copy and paste the exact markdown you're using there so we can reproduce it and add a test case ?

**Comment by bovenson** [comment]
@AaronO I sent two short video via Email to you.

**Comment by bovenson** [comment]
Enable the syntax highlighting will cause this problem @SamyPesse @AaronO

**Comment by Soreine** [comment]
Fixed since 6.3.0
