### ISSUE TITLE
A bug with bulleted list in SUMMARY.md in desktop editor

### ISSUE THREAD

**Issue by orgvueelno** [GitbookIO/feedback#132]
The content in the bullet disappears with enter/ backspace, but it comes back with another action, e.g. space, backspace. I caputured the behaviour in gif. 

![editor bug](https://cloud.githubusercontent.com/assets/14980884/17295875/5da1ec6a-57f6-11e6-9f51-401fea1059e7.gif)

**Comment by SamyPesse** [comment]
Same as #122

Disable syntax highlighting in the settings in the mid time, we are working on fixing this for next releases.
