### ISSUE TITLE
Pasting not working as expected in list 

### ISSUE THREAD

**Issue by jan-matthis** [GitbookIO/feedback#134]
If text is pasted in a bullet list, things are not working as expected -- neither in document mode, nor in the other mode.

Document mode: If text is pasted immediately following the bullet list symbol, the bullet will be removed. 

Other mode: Pasting text in a bullet list is neither possible through `Edit > Paste` nor through the hotkey. This happens immediately after the bullet, as well as when there is preceding text (`- ...`).

Version: Gitbook editor 6.2.1 on OS X.

**Comment by Soreine** [comment]
Will be fixed in version `6.3.0-alpha.1`
