### ISSUE TITLE
Ctrl + V not working

### ISSUE THREAD

**Issue by huangsb** [GitbookIO/feedback#135]
# Bug Report

I press Ctrl + V can't paste text.

My environment is:

- Operating System: Windows 10
- (Desktop) Editor version: 6.2.1

**Comment by ruiyuLee** [comment]
The same issues。

- Mac OS X EI Capitan 10.11.4
- GitBook Editor 6.2.1

**Comment by manngo** [comment]
Ditto Cmd-V on OSX El Capitan 10.11.6, GBE 6.2.1.
Note: Cmd-C _does_ appear to work, and currently I have to resort to finishing the job with right-click.

**Comment by lindexi** [comment]
I cant paster.

**Comment by aloisdg** [comment]
Is it related to #134 ?

**Comment by Soreine** [comment]
Will be fixed in version `6.3.0-alpha.1`
