### ISSUE TITLE
Dialog to insert / edit links should be easier to use for relative links

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/feedback#14]
The dialog should prompt an autocomplete of summary articles and headings (anchors in the page).

For example, here is what it looks like in Google Docs:

<img width="492" alt="screen shot 2016-06-08 at 22 39 08" src="https://cloud.githubusercontent.com/assets/845425/15910121/dd72dc12-2dc9-11e6-8379-bd4dd0b2158c.png">

**Comment by Soreine** [comment]
There's room for improvement, but the main feature is done
