### ISSUE TITLE
Editor 6.2.1 OS X Bug — Copy always appears to copy a single additional line between lines.

### ISSUE THREAD

**Issue by manngo** [GitbookIO/feedback#141]
## Bug Report

Copy always appears to copy a single additional line between lines.

### What is the current behavior?

This is regardless of how many line breaks are between the lines. For example copying this

	one

	two
	three

	four

will result in:

	one

	two

	three

	four

in the clipboard.

### What is the expected behavior?

The line breaks should be copied verbatim.

#### For GitBook Editor

I believe the bug has been around in version 6 for a while, but not necessarily in previous versions.

**Comment by Soreine** [comment]
Will be fixed in version `6.3.0-alpha.1`
