### ISSUE TITLE
Editor 6.2.1 OS X Bug — Right-Click Paste on Selection not working properly.

### ISSUE THREAD

**Issue by manngo** [GitbookIO/feedback#142]
## Bug Report

Given a previous bug report on Cmd-V not working, I need to right-click paste to paste a selection.

### What is the current behavior?

If I select a word in a paragraph, right-click and paste, _the whole paragraph_ is replaced with the clipboard.

Undo will restore and highlight the whole paragraph.

### What is the expected behavior?

Only the selection should be replaced.

Currently I work around this by deleting the old content first, and pasting in the empty space.

#### For GitBook Editor

I can’t remember ever having success with copy & paste in version 6. Not sure about before that.

**Comment by Soreine** [comment]
Fixed in version `6.3.0-alpha.1`
