### ISSUE TITLE
Editor 6.2.1/macOS - Unable to log in with GitBook account

### ISSUE THREAD

**Issue by CharlesWiltgen** [GitbookIO/feedback#144]
### What is the current behavior?

Unable to log in with GBE 6.2.1/macOS. I click "Login using GitBook" in the "Welcome to GitBook!" window, click "Authorize Application" in the windows that appears, and am immediately returned to the "Welcome to GitBook!" window.

I can login via the website without issues.

### What is the expected behavior?

How do you think, or how would you like it should behave.

#### For GitBook Editor

- Operating System? macOS
- (Web) Browser version? n/a
- (Desktop) Editor version? 6.2.1
- Was the bug present in previous versions? (unsure that it's version-specific)

Thank you!

**Comment by SamyPesse** [comment]
It has been fixed (error on server side of GitBook.com).

**Comment by CharlesWiltgen** [comment]
You rock, good sir! 😀👍
