### ISSUE TITLE
Require a Git url

### ISSUE THREAD

**Issue by itwasmattgregg** [GitbookIO/feedback#145]
There is an issue when trying to import another git repo as a new book. After pasting the https url and clicking create book I get the error "Require a Git url" above. The url ends in .git and is a public repo hosted on bitbucket. Also there is no explanation for adding a temporary authentication to the HTTPS url. Is there a tooltip missing?

**Comment by AaronO** [comment]
@itwasmattgregg Thanks for reporting this, I just submitted an internal pull request fixing this issue. It should be deployed tomorrow morning.

To add auth you should be able to add it to the URL like this: `https://username:password@host.com/username/repopath.git`

**Comment by AaronO** [comment]
@itwasmattgregg Just wanted to update to let you know that the fix is live, give it a shot and let me know if it works !
