### ISSUE TITLE
Readme error

### ISSUE THREAD

**Issue by orgvueelno** [GitbookIO/feedback#149]
In this gif example, the article name switches between 'Markdown' and 'How to write in Markdown'. It seems that when selecting 'Introduction' chapter (Readme.md) it changes to 'Markdown' which is an old display name for this article and changes back to 'How to write in Markdown' when selecting other articles. Also the changes made to 'Readme.md' didn't publish. Is it an error with the readme.md? Perhaps I've done something wrong?
![chapter_changes](https://cloud.githubusercontent.com/assets/14980884/17889262/2cd5a5b2-6927-11e6-84ed-71451e2ca470.gif)

**Comment by SamyPesse** [comment]
It looks like a cache issue, is it still happening ?

**Comment by orgvueelno** [comment]
I've resolved it by deleting and creating fresh Readme.md (Introduction).

**Comment by SamyPesse** [comment]
Ok, let me know it it happens again.
