### ISSUE TITLE
User shouldn't be able to activate the devtools

### ISSUE THREAD

**Issue by sateffen** [GitbookIO/feedback#15]
Hey,

more or less a reminder:

Usually a user should not be able to toggle the devtools. _GitBook Editor_ -> _Toggle Devtools_ and _Ctrl + Alt + I_ should both be disabled for the release.

Using version 6.0.0-alpha2

**Comment by SamyPesse** [comment]
I don't think it's an issue. Dev tools can be useful for us to ask for some logs of the user / help him debug something.
