### ISSUE TITLE
Broken github integration, broken updates, missing documentation, no content generated after successful builds

### ISSUE THREAD

**Issue by fedorov** [GitbookIO/feedback#162]
I've been a relatively happy user until the recent update of the website interface. While creating a book yesterday, I ran into multiple issues, as listed here https://github.com/GitbookIO/gitbook/issues/1506. @nagim suggested to move that issue here.

gitbook used to demonstrate the issues listed below: https://www.gitbook.com/book/fedorov/dcmqi-dicom-for-quantitative-imaging

Here are the problems I encountered:
* attempting to link a gitbook to an existing github repo, I am getting this error: 
![image](https://cloud.githubusercontent.com/assets/313942/18092754/8344e600-6e9b-11e6-959e-98c73a9bec0c.png)
* I am not seeing any content under the book I am editing (the UI says 5 updates, and I am getting email notifications about successful updates, but no content to read!):
![image](https://cloud.githubusercontent.com/assets/313942/18092779/9b562344-6e9b-11e6-8285-5f0dc77911be.png)
* this documentation page is blank: https://help.gitbook.com/github/how-can-i-import-repo.html

**Comment by jpreynat** [comment]
Hi @fedorov,

Thanks for your feedback regarding this issue.

Can you give me more informations about the following points:
- Did you try to link to the GitHub repo while creating a new book or an existing one?
- If the book did already exist, did it have any updates before linking?
- Is this a private or public repo on GitHub?
- Is this a private or public book on GitBook?

**Comment by fedorov** [comment]
> Did you try to link to the GitHub repo while creating a new book or an existing one?

I created a new gitbook, and then tried to link it. I did not find an option how to import gitbook directly from a github repo, as I was able to in the past.

> If the book did already exist, did it have any updates before linking?

No, did not exist.

> Is this a private or public repo on GitHub?

Public: http://github.com/qiicr/dcmqi

> Is this a private or public book on GitBook?

Public: https://www.gitbook.com/book/fedorov/dcmqi-dicom-for-quantitative-imaging/welcome

**Comment by fedorov** [comment]
Note that despite the error message, updates done in gitbook web editor propagate to the github repo:

https://github.com/qiicr/dcmqi/tree/gitbook

**Comment by jpreynat** [comment]
Thanks, we are currently publishing a fix for this error.
There might still be some warnings about failing validation on your book's GitHub settings but this should not block the import anymore.

By the way, [here](https://help.gitbook.com/github/can-i-host-on-github.html) is the correct link on the GitBook Help Center about how to link a book to GitHub.

**Comment by fedorov** [comment]
> Thanks, we are currently publishing a fix for this error.

Thanks!

Next time you might consider waiting until issue is factually resolved before closing it.

> By the way, here is the correct link on the GitBook Help Center about how to link a book to GitHub.

The link I mentioned exist, and the page is empty. I am fully aware of the page you mentioned, but it does not describe the process of importing. 

Reading the page you mentioned, I do not get a clear idea what would happen with a non-empty repository if I link it to a new gitbook.

**Comment by fedorov** [comment]
> we are currently publishing a fix for this error

@jpreynat can you please provide the time estimate when I should expect things to work?

As of this moment, no improvements are observed.

**Comment by fedorov** [comment]
I think I figured out one quirk at least - the updates page by default shows master branch, and my updates are not in master. After manually switching to the branch I use, I do see updates.

This issue is related to #165

**Comment by fedorov** [comment]
Alas, I renamed the book, and things do not seem to work again ... I do not see updates under either of the branches, although the tab "Updates" shows "5" ...

https://www.gitbook.com/book/fedorov/dcmqi/details

**Comment by fedorov** [comment]
As of today: selecting gitbook branch -

![image](https://cloud.githubusercontent.com/assets/313942/18129466/e2128940-6f58-11e6-8f7b-a5a3b11440ad.png)


trying to view web based content:

![image](https://cloud.githubusercontent.com/assets/313942/18129475/eca078a4-6f58-11e6-922f-34e712e6bdf6.png)

**Comment by jpreynat** [comment]
Hi @fedorov,

Thanks for your last updates.
There is currently a bug on the page when changing the branch.
If you click on the branch gitbook then reload the page, you will see your updates.
We will publish a fix for this quickly.

However, the web content should be accessible.
We are investigating this and will come back to you when we found the issue.

**Comment by fedorov** [comment]
@jpreynat thanks for reopening the issue!

> There is currently a bug on the page when changing the branch.
> If you click on the branch gitbook then reload the page, you will see your updates.

yes, this works, I see updates after selecting branch and reloading, but I am not able to see the online content

> However, the web content should be accessible.
> We are investigating this and will come back to you when we found the issue.

Right, but it is not. Really look forward to the fix.

**Comment by fedorov** [comment]
This issue appears to be fixed, thank you guys! 👍 

The only remaining thing is empty https://help.gitbook.com/github/how-can-i-import-repo.html, but it is just an annoyance.

**Comment by jpreynat** [comment]
Hi @fedorov,

Thanks for letting us know and closing the issue.
The display issue on your book's updates page will also be fixed in the afternoon.

We will also update the Help Center whenever possible.
Have a nice day.

**Comment by fedorov** [comment]
I am most happy the major roadblock is resolved, and I can again use git books! Other things are really minor.
