### ISSUE TITLE
Application registration

### ISSUE THREAD

**Issue by spolti** [GitbookIO/feedback#164]
I am trying to register an application to use the rest api, but the field `url callback` is required and I don't have much information about what should I put on there, the only thing I have is:

Your application’s callback URL. Read our OAuth documentation for more information.

But the Oauth doc give no clues about it.

**Comment by SamyPesse** [comment]
The url is the callback for oAuth, basically url to which GitBook.com will redirect the user with the auth `code` (see [step 2](http://developer.gitbook.com/overview/oauth.html)).

What is your use case with the GitBook.com API ? :)  
We are still working on the documentation, and we can iterate fast to adapt it to developers use cases.

**Comment by spolti** [comment]
Hi, I just want to retrieve the same result than "https://api.gitbook.com/books" without need to provide token or user/pass. most information are public and any user can get it on browser.
