### ISSUE TITLE
Unable to change default branch in settings

### ISSUE THREAD

**Issue by fedorov** [GitbookIO/feedback#165]
this is the issue with the web interface.

Steps to reproduce (at least, this is the behavior I observe for this gitbook: https://www.gitbook.com/book/fedorov/dcmqi-dicom-for-quantitative-imaging)

1. change default branch from `master` to `gitbook`
2. hit Save
3. observe that default branch is reset back to `master`

**Comment by fedorov** [comment]
Just realized the importance of this issue - user is not able to choose between the branches. What this means is that with this current issue in place, one **must** use master for the gitbook content.

The reason we are avoiding master for developing gitbooks is to not pollute the commit history with the gitbook commits.

Would be very helpful if this issue was fixed.

**Comment by fedorov** [comment]
Same thing happens trying to change the license

**Comment by SamyPesse** [comment]
It should be fixed now. Sorry for the delay, we are working hard on fixing a lot of bugs from the latest major version.

**Comment by fedorov** [comment]
Confirmed - thank you very much! 👍
