### ISSUE TITLE
Questions about search

### ISSUE THREAD

**Issue by agoloprem** [GitbookIO/feedback#170]
Hi,

My team and I are considering using gitbook.com as our team's internal knowledge base to replace our internal wiki. [Here is our Gitbook.](https://www.gitbook.com/book/agolo/wiki/details)

I have 2 questions about search:

1. I noticed that during pageload, a JSON object called `search_index.json` is downloaded to the browser. This contains the text of all chapters, in addition to stems of each token in each chapter. My concern is that when our knowledge base gets to be several MB in size, this will not be scalable. Is there a size limit to the book before this `search_index.json` file no longer gets downloaded?

1. Does our Gitbook have an [OpenSearch](http://www.opensearch.org/Home) endpoint, so I can set it up as a custom search engine in my browser? Ideally, [I want to be able to do this.](https://www.dropbox.com/s/vi9fnjsjp5r6cw5/Screenshot%202016-09-06%2018.13.56.png?dl=0) This would obviate the need for me to bookmark the Gitbook and have to navigate to it every time I want to search something in it.

Thank you!

**Comment by agoloprem** [comment]
I figured out the answer to Question 2 myself. The URL I can use to set up a custom search engine in Chrome is: `https://agolo.gitbooks.io/wiki/content/?q=%s`

Question 1 still stands, though.

**Comment by nagim** [comment]
Hi,

For Question 1, there is a size index limit by default, if the book reaches it, it will stop indexing its content (but that content won't be searchable).

For comparison, my repo has more than 1000 AsciiDoc files, the built book is ~150MB in size (~source is ~60MB with images) and the search index is ~12MB.

**Comment by SamyPesse** [comment]
For Question 1, The search interface can use different backend, the default one is [lunr](https://github.com/GitbookIO/plugin-lunr) which index content in this json file, but you can also use [algolia](https://github.com/GitbookIO/plugin-algolia) (https://www.algolia.com).

**Comment by agoloprem** [comment]
Hi @SamyPesse -- thank you for the prompt response. It was very helpful.

I have a question about running Algolia. The `README` has the following step:

> Finally, pass your Admin API Key as an environment variable when launching gitbook, using ALGOLIA_PRIVATEKEY:

```
$ ALGOLIA_PRIVATEKEY="algolia-admin-api-key" gitbook serve
```

Is it possible to set environment variables on our book that's hosted on gitbook.com? I can't find anything about it in [the Gitbook docs.](https://ganiutomo.gitbooks.io/gitbook-documentation/content/book/variables.html)

**Comment by SamyPesse** [comment]
@agoloprem yes, in the book settings you can specify environment variable:

![screen shot 2016-09-07 at 16 24 42](https://cloud.githubusercontent.com/assets/845425/18315523/9f60b134-7517-11e6-9c15-7bc98c8edca0.png)

We'll add an entry in the FAQ about this.
