### ISSUE TITLE
git URL is missing from the GUI

### ISSUE THREAD

**Issue by nagim** [GitbookIO/feedback#173]
Hi,

The git URL of the book was displayed in the old GUI, but cannot be found in the new one.
Might be good to bring it back to the **Updates** page.

Thanks,
Imre

**Comment by SamyPesse** [comment]
The url is accessible using the ⬇️  on the Edit button:

![screen shot 2016-09-09 at 17 12 31](https://cloud.githubusercontent.com/assets/845425/18392055/9d69c038-76b0-11e6-8025-522c85bd66f2.png)

**Comment by nagim** [comment]
Aahh, I couldn't find it anywhere, thanks a lot! :-)
