### ISSUE TITLE
Raw mode: add table row on Enter

### ISSUE THREAD

**Issue by sherlockking** [GitbookIO/feedback#180]
When I add the label `<br>` for a newline within a table in the markdown editor, I just cannot find the corresponding change in the preview window. As shown in the figure:
![table](https://cloud.githubusercontent.com/assets/17003820/18466029/6cedf1da-79cc-11e6-8883-dc1703e52670.png)
And I wish that I can add a new line just with a return key.

**Comment by Soreine** [comment]
The published book should take the `<br>` tag into account.
I tag this as feature request.
