### ISSUE TITLE
Editor - It's not easy/natural to write out of a link

### ISSUE THREAD

**Issue by hanoii** [GitbookIO/feedback#182]
### What is the current behavior?

If I select the last words to be a link to something, if I continue to write on the same line, the texts keeps being wrapped up within the link title. The only way to make it go out of the link is hitting enter, writing something, then doing a backspace and keep on writing from the previous not link letter.
### What is the expected behavior?

Something more natural, like either clicking an arrow, or double space or something to tell the editor that I want to close the link wrapping. 
#### For GitBook Editor
- Operating System?
  OSX 10.11.6
- (Desktop) Editor version?
  6.2.1
- Was the bug present in previous versions?
  Fist version I tried.

**Comment by Soreine** [comment]
This is fixed for usual cases
