### ISSUE TITLE
Support Markua

### ISSUE THREAD

**Issue by shadowbq** [GitbookIO/feedback#184]
#### For GitBook

Support Markua as a text md processor  

https://leanpub.com/markua/read

https://github.com/markuadoc/markua-js

The GitBook Team

**Comment by Soreine** [comment]
While Markua is a good project on its own, I don't think we will ever want to work on supporting another syntax. Unless it becomes the new Markdown, we will keep our focus on gitbook features, and will continue to consider the supported syntax to be close to an implementation detail.
