### ISSUE TITLE
403 Forbidden when attempting to edit my private book

### ISSUE THREAD

**Issue by vesche** [GitbookIO/feedback#188]
### What is the current behavior?

Went to edit my private book via a URL similar to this:
https://www.gitbook.com/book/username/book-name/edit

And recieved a 403 Forbidden page saying, "The plan of the author of this book appears to be invalid. Please check your settings before retrying."

I am logged in, and was able to edit this book succesfully 2 days ago.

### What is the expected behavior?

Well, I should be able to edit my book. :smile: 

#### For GitBook Editor

- Operating System? Arch Linux (4.7.1-1)
- (Web) Browser version? Mozilla Firefox 48.0.2
- (Desktop) Editor version?
- Was the bug present in previous versions? No.

I tested this bug on Windows and Android with a similar result.

#### For GitBook.com

Username: vesche

----

The GitBook Team

**Comment by jpreynat** [comment]
Hi Austin,

Sorry but this is not an issue.
Your current plan on gitbook.com don't allow for creating private books.
You actually encountered a bug before, when you were able to do it.

If you want private books, you have to subscribe to the [Plus plan](https://www.gitbook.com/pricing).

Have a nice day.
Johan

**Comment by vesche** [comment]
Johan,

What? Then when why was I at all allowed or able to make a private book? This is an issue. I figured that GitHub and GitBook shared membership because I was allowed to create AND edit a private book for TWO days. If it's required to pay separately for GitBook than don't give me a 403 Forbidden after I've been able to access it..... How am I supposed to know what's going on??? Have it say "GitHub membership is not the same as GitBook membership". Eitherway it's discomforting for a fellow developer to call this a non-issue and move on.

**Comment by SamyPesse** [comment]
@vesche We are [not related to GitHub](https://www.gitbook.com/about), [GitBook's pricing](https://www.gitbook.com/pricing) is totally separated from GitHub.

Sorry for this error, it was a regression in a recent deployment.

Happy to give you a coupon so that you can continue working on your book.
