### ISSUE TITLE
Where is the clone url?

### ISSUE THREAD

**Issue by sheldonth** [GitbookIO/feedback#189]
I have created two repositories and looked closely all over the page and I cannot find the url I should clone.

What am I missing?

Edit: by "url I should clone" i mean to access with the repo which has the standard format for git book setup ready to start accepting markdown. If that assumption is incorrect, let me know. Thanks.

**Comment by nagim** [comment]
It should be in the dropdown menu of every **Edit** button. Click on the arrow next to it.

![image](https://cloud.githubusercontent.com/assets/16205115/18777149/f370f506-816d-11e6-86bf-79019bc3a553.png)

**Comment by sheldonth** [comment]
<img width="1086" alt="screen shot 2016-09-23 at 11 49 07 am" src="https://cloud.githubusercontent.com/assets/733784/18792287/da595692-8183-11e6-9faf-7c8234336be7.png">
Wut

**Comment by sheldonth** [comment]
It's not there?

**Comment by jpreynat** [comment]
Hi @sheldonth,

This button is accessible when clicking on your book's `updates` tab.
We will think of a way to make it more easy to find.

Kind regards.

**Comment by sheldonth** [comment]
Wow. Okay -- that was hard to find. Deep thanks! And I'm still going to take this service for a test drive. I go like the command line tool and the format specification.

Some more features/feedback/questions
- Is there a way to disable the Title bylines and horizontal rulers on the pdf output?
- The pdf generator skips emoji codepoints. 
- How do you indent a paragraph?

**Comment by jpreynat** [comment]
Hi @sheldonth,

The next update of GitBook.com will integrate this dropdown button on the welcome page for your new books.
Thanks for your feedback.

In consequence, I'm closing this issue.
Could you please open another one regarding your questions about the PDF format?

Kind regards
