### ISSUE TITLE
Editor 6.3.0-alpha1 - asciidoc syntax highlight

### ISSUE THREAD

**Issue by nagim** [GitbookIO/feedback#197]
Hi,

In raw mode, the Editor tries to apply Markdown syntax highlighting to AsciiDoc files, too.
Win 7 Pro 64-bit.

Thanks,
Imre

**Comment by nagim** [comment]
Hi,

It's still and issue in beta3.

Cheers,
Imre

**Comment by SamyPesse** [comment]
It should be fixed in `6.3.2`.

**Comment by nagim** [comment]
Tested and works, thanks a lot! :clap: 
Could #47 be solved, too, please? :smiley:  Thanks again!
