### ISSUE TITLE
Editor 6.3.0-alpha1 - relative vs. absolute links

### ISSUE THREAD

**Issue by nagim** [GitbookIO/feedback#199]
Hi,

I saw that from now on, Editor inserts absolute links, which is great... if you can use GitBook >=3.x.x.
Lot of us are still on 2.6.7 for various reasons, but the absolute links will not work there.

Thanks,
Imre

**Comment by Soreine** [comment]
The Editor v6 is made for Gitbook >=3 primarily. So I'm closing this issue, since the goal is for everyone to move to GitBook 3.

**Comment by nagim** [comment]
I understand the reasoning, although there are still pending issues that prevent moving to GitBook v3.
