### ISSUE TITLE
Old version of content before refresh

### ISSUE THREAD

**Issue by natenka** [GitbookIO/feedback#204]
### What is the current behavior?

Every time I create a new chapter or update text, I can't see updates from the other chapters and subchapters until I press refresh in browser.

For example, I have content:
1. intro
1.1 subintro
2. chapter1

And create 3. chapter3

If I go to chapter3 in web version, I can see all chapters.
But, when I switch to intro, I don't see chapter3.
Press refresh in browser and it magically appears.
But I need do the same with all chapters and subchapters - go to each and press refresh to see updates.
#### For GitBook Editor

I see this behavior in Chrome on Mac OS (Version 49.0.2623.87 (64-bit)) and in mobile phone.

I'm update book from the github repo (for gitbook online editor all was the same).
#### For GitBook.com

Book: https://www.gitbook.com/book/natenka/pyneng/details
User: natenka
Github repo: https://github.com/natenka/PyNEng

**Comment by Soreine** [comment]
It's because of the way the published gitbooks are fetched. If you navigate using the summary, it will not reload the whole page, but just the chapter's content. That's why it does not refresh the summary itself.

**Comment by Soreine** [comment]
It is done this way for efficiency, and I think the advantages outweigh the inconveniences.
