### ISSUE TITLE
Editor 6.3.0-alpha1 Very Slow and Unresponsive

### ISSUE THREAD

**Issue by manngo** [GitbookIO/feedback#207]
When editing a file, it takes a long time to accept keystrokes.

For example, if I press Return twice, I have to wait a matter of seconds before I see a new line. If I press delete/backspace, it takes a few seconds to respond to that, and may miss one of the keystrokes. Sometimes if I press Cmd-Arrow (home or end) it takes a few seconds to respond to that, and sometimes doesn’t land in the correct location.

Cmd-X (cut) takes a few seconds. Cmd-V and Cmd-Z also.

I don’t know whether this is related or a new issue, but Cmd-Z Undo doesn’t undo very far.
- Operating System? MacOS 10.12 Sierra

**Comment by nagim** [comment]
Hi,

The performance thing is a known issue, they're working on it.
I think you should create a separate issue for the Undo behaviour.

Cheers,
Imre

**Comment by SamyPesse** [comment]
We just released the first beta of 6.3.0, you can download it and read the full changelog at [gitbook.com/editor/releases/all](https://www.gitbook.com/editor/releases/all).

It greatly improved editing performance.
