### ISSUE TITLE
New dashboard home filters

### ISSUE THREAD

**Issue by orgvueelno** [GitbookIO/feedback#236]
Feature requests

I quite liked the way it worked in the previous version where I can quickly filter by account names and tags from the side navigation on the right hand side. Honestly don't see much benefits of tile display. Also the tiles are not suitable for those with longer book titles.

**Comment by SamyPesse** [comment]
@orgvueelno Let me know what you guys think of the new dashboard.

**Comment by orgvueelno** [comment]
Looks great. Would be nice to have tags back to the book list as well and New Book buttons being in 2 places can be confusing. And separately on the New Editor, 2 terms should be tweaked/ streamlined:
1. Publish: Should be 'Save & Publish' when you're in master branch, and 'Save' when you're in non master branch
2. Create a new version: in the pop up window it uses the term 'branch'. Whether i'ts version or branch need to be sorted. It is confusing for new and non technical users

**Comment by SamyPesse** [comment]
I just released a new version of GitBook.com which includes the tags on the dashboard.

Concerning the other points:

1. That's a good idea, we'll think about it
2. I agree, but basically our plan is to release some important collaboration features related to branches in the next few months, and to tackle these UX issues at the same time.
