### ISSUE TITLE
Two lines description of books breaks style of preview cards

### ISSUE THREAD

**Issue by DoumanAsh** [GitbookIO/feedback#238]
See example http://i.imgur.com/lbbnXsx.png

Seems like it wasn't intended to have short description longer than two lines but it is possible to have it.
So  Edit & Read buttons are placed near border

Maybe force limit on description of book?

## Category

Bug?

## What is the current behavior?

See example http://i.imgur.com/lbbnXsx.png

## What is the desired behavior?

Consistent style regardless of how big is description

## Additional information

Specs: Win10 x64, Firefox 50 (the same seen in Chromium 57.0.2926.0 and i suspect other browsers too)

My suggestion is  to remove height (since flex is used there will be no issue) but cards will not retain the same size.
http://i.imgur.com/MWaWDXU.png

I do not see an issue in it, but some might fin it unpleasant.
Though current situation is worse, i think.

**Comment by DoumanAsh** [comment]
P.s. in case if you're wondering bigger descriptions will break style completely
http://i.imgur.com/09SIa6U.png

Forcing height is bad... when you cannot control size of content :)

**Comment by DoumanAsh** [comment]
I believe it has been fixed with current new design of dashboard?

**Comment by SamyPesse** [comment]
Yes, thank you, I'm closing this issue.
