### ISSUE TITLE
Editor 6.3.0-beta3 - rich text copy-paste with link

### ISSUE THREAD

**Issue by nagim** [GitbookIO/feedback#240]
Hi,

The rich text copy-paste in the newest beta is just awesome :smile: :clap: .
However, if I copy an HTML content with links and paste it, the spaces before and after the link text are removed.

Example result:
![image](https://cloud.githubusercontent.com/assets/16205115/20744738/f67f7448-b6dd-11e6-8c11-df7407b357d4.png)

Thanks,
Imre

**Comment by SamyPesse** [comment]
Related to https://github.com/GitbookIO/markup-it/issues/34
