### ISSUE TITLE
The git manager process has crashed. Please restart your application

### ISSUE THREAD

**Issue by jakeoung** [GitbookIO/feedback#242]
## Category

bug report

## What is the current behavior?

I have an error for Gitbook editor, after updating 6.3.0 on Mac 10.12.

If I launch my app, it says that

>"The git manager process has crashed. Please restart your application"

I have removed previous versions and reinstall, but it doesn't work.

I even couldn't log in.

**Comment by AaronLasseigne** [comment]
I have the same issue on 10.11.

**Comment by imbacile** [comment]
Same problem.

**Comment by SamyPesse** [comment]
Can you send me the content of `~/Library/Application\ Support/gitbook-editor/log-app.log` (OS X) at `samy@gitbook.com` ?

**Comment by imbacile** [comment]
Done.

**Comment by o0runner** [comment]
Same problem.

**Comment by SamyPesse** [comment]
We just released the version 6.3.1, it should fix this issue. Otherwise send me the output of the log file `~/Library/Application\ Support/gitbook-editor/log-app.log` by email.
