### ISSUE TITLE
gitbook editor 6.3.0  dis-fluency when using Chinese input method，window 10 and window 7 both involved.

### ISSUE THREAD

**Issue by HuanGong** [GitbookIO/feedback#244]
## gitbook editor 6.3.0  

gitbook editor 6.3.0  dis-fluency when using Chinese input method，window 10 and window 7 both involved.

Thanks for your great Job

**Comment by SamyPesse** [comment]
Thanks, It seems to be a duplicate of #232

Closing this one.

**Comment by HuanGong** [comment]
good job, thanks. it seems ok in version 6.3.7
