### ISSUE TITLE
Math equation bug in raw edit mode

### ISSUE THREAD

**Issue by jakeoung** [GitbookIO/feedback#249]
![image](https://cloud.githubusercontent.com/assets/2376897/21004852/d3a22eae-bd75-11e6-8591-028b9b735f15.png)

Even if it is in raw mode, the rendered equations appear. I just want **raw text**.

- What Operating System are you using? Mac
- (Web) What is you browser version?
- (Desktop) What is the version of the Editor you are using? Gitbook editor 6.3.3
- Was the bug present in previous versions? Yes.

**Comment by jakeoung** [comment]
Now even in web editor, the raw editor is not a raw editor. When the equations are added, it shows weird renderings.

**Comment by SamyPesse** [comment]
@jakeoung This issue should be fixed in today release (it'll live for everybody in a few hours).

It was a bug, the raw editor should be raw.
