### ISSUE TITLE
Add anchor link to headers within a page

### ISSUE THREAD

**Issue by DoumanAsh** [GitbookIO/feedback#251]
## Category
Feature request

## What is the current behavior?
Each header within page has own id.
So it is possible to use anchor.
But there is no easy way to just click on link near header like in rendered README file on github.com

## What is the desired behavior?
It would be great to add a similar anchor link like for rendered README file on github.com
E.g. https://github.com/DoumanAsh/lazy-command.py#examples

## Additional information
This will give reader possibility to have bookmark within one big page.
While it can be worked around by fragmenting pages, it is sometime might be desirable to have big page.

**Comment by Soreine** [comment]
This is a feature that will be present by default in GitBook v4

**Comment by DoumanAsh** [comment]
Ok, this is already merged to v4 branch?
Then i suppose this issue can be closed
