### ISSUE TITLE
Can not indent with tab

### ISSUE THREAD

**Issue by jeschou** [GitbookIO/feedback#252]
## What is the current behavior?

can not use tab to indent, focus will lost.

## What is the desired behavior?

When type Tab key, i want to insert a tab character or  4 space.

but now, i can only use space key to indent.

## Additional information

OS: Mac OSX Sierra 10.12.1
Browser: Safari 10.0.1
GitBook Editor Version: 6.3.5 (same problem with previous version)

**Comment by genie137** [comment]
I can report the same happens on Linux.

**Comment by genie137** [comment]
Just noticed the same happens in the web editor. (Using Chrome 55.0.2883.75 64-bit on Linux Ubuntu 16.10)

**Comment by SamyPesse** [comment]
Fixed in version `6.3.7`

**Comment by Soreine** [comment]
In Raw mode or inside code blocks, you should now be able to use Tab to indent (version 6.3.7)
