### ISSUE TITLE
Back-ticks must follow a blank?

### ISSUE THREAD

**Issue by derekey** [GitbookIO/feedback#253]
## GitBook Editor
Bug report

## Back-ticks not work, it must follow a blank?

![1](https://cloud.githubusercontent.com/assets/11836492/21037145/4e5863da-be06-11e6-986f-0881e71226d2.png)

![2](https://cloud.githubusercontent.com/assets/11836492/21037151/56abefde-be06-11e6-9919-36efd4098d09.png)

## Additional information
    - osx 10.11.6
    - version 6.3.5

**Comment by Soreine** [comment]
"```" are for code blocks, and must be followed by a blank line (with optional language syntax):
"`" are for inline code, and don't require blanks.

Your example would work fine like this:

    `This`is

    ```js
    This file is an example configuration
    ```

**Comment by Soreine** [comment]
Sorry, you're actually right. It is even supported by GitHub. We're investigating.

**Comment by derekey** [comment]
TX.

**Comment by AaronO** [comment]
Hi @derekey, I noticed you were using "raw mode" instead of the WYSIWYG "document mode", is there a specific reason why ?

Would appreciate your feedback :)
