### ISSUE TITLE
[Bug] math block is not rendered

### ISSUE THREAD

**Issue by AlbertZed** [GitbookIO/feedback#254]
For example,
$$R_+$$ as the interval $$[c, r_+]$$ where $$r_+$$ is a pt to the right of c such that Pr$$[c, r_+]$$ is $$\epsilon$$.

The new parser is somehow trying to skip the first $$ and displays from R_+$$ as the interval $$[c, r_+]$$ where ...

Mac
Gitbook Web Editor
New bug after the most recent update

Please fix this

**Comment by AlbertZed** [comment]
Code block is also not rendered. Am I on an alpha/beta testing cohort?? 
The web editor is so buggy after updating to a new look.

**Comment by SamyPesse** [comment]
@AlbertZed You can use the Raw mode while we debug this issue:

<img width="380" alt="screen shot 2016-12-09 at 23 15 13" src="https://cloud.githubusercontent.com/assets/845425/21066346/62af3ea8-be65-11e6-8476-bd54be4ea0ce.png">

**Comment by AlbertZed** [comment]
Hi @SamyPesse, thanks for responding. I know you guys are trying to improve the user experience. But the issue is the web editor is so buggy that the raw view doesn't even for the math block bug I mentioned above.

**Comment by SamyPesse** [comment]
This issue should be fixed with today release (it should be live for everybody in a few hours).

We are working hard on improving performances and the experience.
