### ISSUE TITLE
Shift + Tab not working any more

### ISSUE THREAD

**Issue by energyd** [GitbookIO/feedback#257]
## Category

Bug

## What is the current behavior?

Shift + Tab to reduce indent, and nothing will happen

Also sometimes backspace key will act like enter key

Also one minor thing is the save button becomes publish button, don't know why

## What is the desired behavior?

Should reduce indent properly

## Additional information

No

**Comment by SamyPesse** [comment]
In raw mode (edition of markdown) or document mode ?

**Comment by energyd** [comment]
Both mode....Since sometime last week, it totally broke down for me... Seems you guys pushed a new version? Because the appearance changed a lot...

**Comment by Soreine** [comment]
This should have been fixed since 6.3.10
