### ISSUE TITLE
gitbook.com online editor: Leave unsaved changes in one browser and edit it into another browser

### ISSUE THREAD

**Issue by DoumanAsh** [GitbookIO/feedback#259]
It is a big difficult to explain.
But here is situation that occurred to me.

I started edit of my book in Firefox, but i closed it without publishing.
Then i went to Chromium, made some changed and published it.

Now when i open my book in edit mode by Firefox, i still see my old changed that are pending to be published.
I tried to clean everything cache, cookies, offline data...
But it still remains and there is no way to abort all these pending changes.

## Category
Feature/bug?

## What is the current behavior?
No way to abandon all pending changes after re-opening book in browser

## What is the desired behavior?
Have some way to abandon all pending changes.

## Additional information
Specs: Win10 x64, Firefox 50.0.2

**Comment by Soreine** [comment]
Indeed, the Editor stores unsaved changes, to avoid losing unfinished work if the browser is closed, crashes, etc.
However, I think we should prompt on opening that "some unsaved changes can be restored" and offer to either pick up the unsaved changes, or discard them.

As a temporary workaround, you can discard manually all your changes. The easiest way is to go the the files view, Right-click on every files that has a colored indicator, and choose "Discard changes". You will be done when the Publish button is grayed out. After that, close the Editor and reopen it.

**Comment by DoumanAsh** [comment]
@Soreine thanks for a tip.
it is though curious where these changes are saved? I assume it is not saved within browser?

**Comment by Soreine** [comment]
The state of the editor is saved within the browser, serialized to the local storage, at a regular time interval, and also right before closing the tab.
