### ISSUE TITLE
Additional heading types in the toolbar

### ISSUE THREAD

**Issue by jonjomckay** [GitbookIO/feedback#260]
## Category

Feature request for the GitBook Editor.

## What is the current behavior?

H1, H2 and H3 are displayed in the toolbar.

## What is the desired behavior?

All 6 heading types to be displayed in the toolbar.

## Additional information

I'm using the GitBook Editor 6.3.8 on OS X 10.11.6.

It'd be awesome if all the heading types supported were displayed in the toolbar (and the right-click menu too). Currently, my book uses H1-H5 but to add in or modify my H4 and H5 headings I have to switch out of document mode and manually edit the Markdown which is a bit of a hassle. I noticed in the screenshot on the [editor homepage](https://www.gitbook.com/editor), H1-H5 are displayed in the toolbar, but they don't seem to be in my editor or customisable :(

**Comment by SamyPesse** [comment]
You can type `#### ` in document mode to trigger an heading H4 (`##### ` for an H5, etc).

We removed the `H4 -> H6` button to avoid clustering the toolbar, but we might be considering other solutions.

**Comment by Soreine** [comment]
We could add a fourth dropdown button `H#` that offers the H4, H5, H6 options

**Comment by jonjomckay** [comment]
If adding explicit buttons for `H4 -> H6` isn't an option, I think @Soreine's suggestion of a dropdown containing the others would be a good compromise
