### ISSUE TITLE
buttons not working in Windows 10

### ISSUE THREAD

**Issue by huaweichen** [GitbookIO/feedback#268]
## Category
GitBook Editor

## What is the current behavior?

1. press 'TAB' button, does not work.
2. Sometimes, 'backspace' and 'del' button, behave as 'Enter'
3. 'Ctrl + x' not work
4. 'Ctrl + z' not work.

    Thank you! GitBook Team

**Comment by Soreine** [comment]
Hello,

Can you confirm that 1. and 2. are still present in latest version 6.4.0 ?
Could you describe when, and how `Ctrl+X` and `Ctrl+Z` don't work ?

Thank you
