### ISSUE TITLE
Dashboard: Display truncated book's titles and description on hover

### ISSUE THREAD

**Issue by shadowbq** [GitbookIO/feedback#274]
On the gitbook-editor (6.4.0) , we need a list view for the available books. Many of our books start with a formula repo name that is company_project_books_subproject  .. We end up having "..." truncating docs making it nearly impossible to select the correct gitbook. A hover to full name would help as well over the book name, to untruncate.

## Category

FR: List view when selecting book

## What is the current behavior?

The name of the book is truncated with "..."

## What is the desired behavior?

Create a sortable column based list view of available gitbooks
A hover over the "..." to switch/hint full name would help

## Additional information

Windows & Linux 
Gitbook Editor 6.4.0

**Comment by Soreine** [comment]
We are thinking of the best way to display books on the Dashboard. We are aware of the current issues of usability with the card-style dashboard. Your suggestion for hover is an easy improvement we can make before anything else.
