### ISSUE TITLE
Cannot create a new book with github repo

### ISSUE THREAD

**Issue by VincentPat** [GitbookIO/feedback#299]
I just delete a book and then I can't create a new one...
Now I find no answer to this problem.
How could this happen?

<img width="1280" alt="2017-01-10 12 54 40" src="https://cloud.githubusercontent.com/assets/13195247/21774997/64a64eae-d6cf-11e6-8abe-3cf8e60b21a8.png">

**Comment by SamyPesse** [comment]
We're deploying a fix, it should be fixed in a few minutes.

**Comment by VincentPat** [comment]
Oh, thx.
