### ISSUE TITLE
After moving uploaded images from assets directory it is impossible to access them

### ISSUE THREAD

**Issue by DoumanAsh** [GitbookIO/feedback#304]
Way to reproduce.

1) Upload any image by drag & drop. It will be stored in assets directory (you can see it)
2) Move image from this directory to other directory (in my case newly created img_finale).
3) Image isn't available either through file browser in editor or when you link it in text.

Continuously loading while my older images are perfectly fine.
http://i.imgur.com/F6FAJBu.png

**Note:** Publish also doesn't change anything

## Category
Seems like a bug

## What is the current behavior?
After uploading images by drag & drop and moving them to some other location, it is no longer possible to access it.

## What is the desired behavior?
Obviously retain ability to access it.

## Additional information
**Version:** Gitbook.com
**Book:** https://www.gitbook.com/book/doumanash/trails-of-cold-steel-2-walkthrough/details
**Browser:**  Chromium 57.0.2970.0 (64-bit)

**Comment by SamyPesse** [comment]
Fixed in `7.0.0`.
