### ISSUE TITLE
Default shortcuts conflict with the use of Alt Gr

### ISSUE THREAD

**Issue by lgarcin** [GitbookIO/feedback#305]
## Category

Editor

## What is the current behavior?

Can't input characters with Alt Gr key with a french keyboard : pipe ( | ), opening bracket ( [ ), opening curly bracket ( { ).

## What is the desired behavior?

Input the aforementioned characters.

## Additional information

OS : Windows 10 64bit pro
Browser : Chrome
Gitbook Editor v6.5.2

**Comment by Soreine** [comment]
This is because of the keyboard shortcuts for Headings 4, 5, and 6 that use `Alt+Ctrl` which is equivalent to `Alt Gr`. You can rebind them from the Editor settings.
I am looking for better default shortcuts right now.

**Comment by Soreine** [comment]
Fixed in 6.6.1
