### ISSUE TITLE
Impossible to get information on the procedure about getting educational discounts

### ISSUE THREAD

**Issue by fedorov** [GitbookIO/feedback#314]
## Category

This is a bug

## What is the current behavior?

No response is received for about 6 months after requesting information following the instructions at https://help.gitbook.com/accounts/do-you-offer-discounts.html. My specific request was submitted on July 11, 2016, and assigned number 3538 by the automated system. Several reminders and messages on slack were sent over the course of past 6 months, still no response.

## What is the desired behavior?

Get clarification about the procedure of getting educational discount for the specific project/account from gitbook support.

## Additional information

Numerous users complained about this on the `#plans_and_signup` channel of gitbook slack. No response was ever received.

**Comment by Soreine** [comment]
We are sorry that your request was not answered. We do have received an request on July 11, about full text search. But nothing about Educational discounts. Could you please open a request, or send me an email with your initial message at soreine@gitbook.com?

I have updated the [FAQ entry for discounts](https://help.gitbook.com/accounts/do-you-offer-discounts.html), indicating what we expect from an application. 

We are a small team, and we sometimes cannot handle the amount of requests we receive, I hope you understand that we do our best and that we are continuously working on improving our effectiveness.

**Comment by fedorov** [comment]
I emailed Soreine with the details and a copy of the original request. Should I bug you again in a week? month? if I don't hear back

I do understand that you are a small team, but I've been waiting for 6 months! 

I would be more than willing to pay subscription fees if I knew this will expedite response time. I think if you guys added "improved customer support" as a perk for subscription, you would raise a lot of money.

**Comment by fedorov** [comment]
Thank you, I received the response - issue resolved!
