### ISSUE TITLE
Templating syntax is parsed inside code blocks

### ISSUE THREAD

**Issue by Mackiovello** [GitbookIO/feedback#316]
## Category

Bug during build

## What is the current behavior?

Polymer bindings in HTML code blocks are treated as templates which make the bindings disappear after building.

For example, if you have this code:
```
```html
<template>
    <template is="dom-bind">
        <h1>{{model.FirstName}}</h1>
        <h3>{{model.LastName}}</h3>
    </template>
</template>
```

The output will look like this in the current situation:
![capture](https://cloud.githubusercontent.com/assets/19392292/22061663/5179bd0e-dd76-11e6-8a11-33c690f34a87.PNG)

## What is the desired behavior?

Polymer bindings inside code blocks should be displayed.

## Additional information

I have tried with both highlight.js and prism. The same issue occurs with both.

CLI version: 2.3.0
GitBook version: 3.2.2

**Comment by Mackiovello** [comment]
When taking a closer look, it seems like this is a recent issue. Polymer bindings in code built a couple of weeks ago did not disappear. Copying those pages and building them again today makes the disappear.

**Comment by SamyPesse** [comment]
This is really weird with version 3.2.2 (which has been stable for a long time). Is your book on GitBook.com ?

Basically code blocks should be escaped from GitBook templating syntax (which conflicts with Polymer bindings.

One solution is to manually escape the code block:

    {% raw %}
    ```html
    <template>
        <template is="dom-bind">
            <h1>{{model.FirstName}}</h1>
            <h3>{{model.LastName}}</h3>
        </template>
    </template>
    ```
    {% endraw %}

**Comment by Mackiovello** [comment]
Yea, it's [here](https://www.gitbook.com/book/mackiovello/docs/details)

Using {% raw %} works

**Comment by lazaridis-com** [comment]
@Soreine , @AaronO 

minimal (immediate) action: place a remark in Gitbooks documentation, like:

"if you have content in the form `{{model.FirstName}}` you have to escape it with ..."

**Comment by Soreine** [comment]
@lazaridis-com Thanks for the suggestion

**Comment by lazaridis-com** [comment]
fixed within GitbookIO/gitbook@7fc1e02 and GitbookIO/gitbook@bc315a1

@Mackiovello @Soreine , i guess this issue can be closed now.

**Comment by Mackiovello** [comment]
Do we have any update on fixing this issue?

**Comment by Mackiovello** [comment]
Closing due to move to the new version where this issue does not exist
