### ISSUE TITLE
Multiline string in C# block causes Template render error

### ISSUE THREAD

**Issue by Mackiovello** [GitbookIO/feedback#317]
## Category

Bug with templating

## What is the current behavior?

When using this code-block:
```
```cs
var html = @"
<head>
    <style>
        body {{
            margin: 20px;
        }}
    </style>
</head>";
Application.Current.Use(new PartialToStandaloneHtmlProvider(html))
```
I get the following error:

```
Template render error: (C:\Users\Mackiovello\Documents\Documentation\test-gitbook\sub-page-two.md) [Line 6, Column 19]
  expected variable end
```
## What is the desired behavior?

There should be no error because the code is within a code block.

## Additional information

CLI version: 2.3.0
GitBook version: 3.2.2

**Comment by nagim** [comment]
You have to escape the {{ }} parts as this is similar to the templating syntax.
Enclose the problematic parts in {% raw %} {% endraw %}.
So it would look like this:

```cs
{% raw %} 
var html = @"
<head>
    <style>
        body {{
            margin: 20px;
        }}
    </style>
</head>";
Application.Current.Use(new PartialToStandaloneHtmlProvider(html))
{% endraw %}
```

**Comment by nagim** [comment]
Ah, just saw on Slack that you've also figured it out... :smile:

**Comment by Mackiovello** [comment]
From what @SamyPesse said:

> Basically code blocks should be escaped from GitBook templating syntax (which conflicts with Polymer bindings.

I thought that this might be a bug that probably should be fixed. It's not a big deal, though it was annoying when I first hit it.

**Comment by Soreine** [comment]
The root of this issue is the same than https://github.com/GitbookIO/feedback/issues/316
The templating syntax for variables `{{ ... }}` should not be parsed within code blocks.
I'll close this issue in favor of the other.
