### ISSUE TITLE
The first time you start Gitbook Editor, will pop up this error message.

### ISSUE THREAD

**Issue by netcmcc** [GitbookIO/feedback#318]
The first time you start Gitbook Editor, will pop up this error message.

> A JavaScript error occurred in the main process
> 
> Uncaught Exception:
> Error: ENOENT: no such file or directory, open '/Users/cmcc/Library/Application Support/gitbook-editor/log-app.log'
>     at Error (native)

Analyze the cause of the error，if “/Users/cmcc/Library/Application Support/gitbook-editor” When the directory does not exist, this prompt will pop up. Delete this directory (gitbook-editor), restart the GitBook Editor once to reproduce the scene.

Previous versions of this problem exist

## Category

Bug
Gitbook Editor

## Additional information

  For the GitBook Editor:
    - Operating System macOS 10.2.2
    - (Web) Browser version
    - (Desktop) Version of the Editor 6.5.2
  For GitBook.com:
    - Your username
    - When possible, the URL of the book

**Comment by Soreine** [comment]
This should be fixed in the upcoming release (already fixed in the Beta version)
