### ISSUE TITLE
GitBook mac client crash when I insert character after code region

### ISSUE THREAD

**Issue by zhenzong** [GitbookIO/feedback#319]
## Category
mac client crash

## What is the current behavior?
When I try to type a character, no matter English or  Chinese, after  markdown code region, mac client will occur to crash, but number is ok. But sometimes  it work fine, so, I am not really sure what I do lead to client crash. Maybe error log can help us, but I don't know where is log.

code region just like below:

``` java
@Override
public void setAsText(String text) {
    String pattern = resolvePath(text).trim();
    try {
        setValue(this.resourcePatternResolver.getResources(pattern));
    }
    catch (IOException ex) {
        throw new IllegalArgumentException(
            "Could not resolve resource location pattern [" + pattern + "]: " + ex.getMessage());
    }
}
```

## What is the desired behavior?
Gitbook mac client can work fine no matter what  I write. And if client can **save file before crash** or **recover file after crash**,  that couldn't be better.

## Additional information

Operating System: MacBook Pro (Retina, 13-inch, Mid 2014)
Version of the Editor: version 6.5.2

**Comment by Soreine** [comment]
Hello,

It's difficult to reproduce the issue. We have improvement to code editing, planned for the next release. But it might not be related to your crash.
Do you have the link to a book and document where you experience this crash? Or could you paste (or send at soreine@gitbook.com) the content of a document that crashes?
