### ISSUE TITLE
When I insert a link, I want the link text derived from the SUMMARY file by default

### ISSUE THREAD

**Issue by jaredmorgs** [GitbookIO/feedback#320]
## Category

* Feature Request
* GitBook Editor

## What is the current behavior?

![screen shot 2017-01-19 at 9 46 04 am](https://cloud.githubusercontent.com/assets/952793/22102476/4b09bc72-de83-11e6-9afc-12bd01f8a94c.png)

I'm using the `link` function in a book to add in jumps to other articles in my book.

I love how you get the rendered name of the file when you type.

What I find a real disconnect is that when the link goes into the book, it is naked.

![screen shot 2017-01-19 at 9 48 08 am](https://cloud.githubusercontent.com/assets/952793/22102703/1c49c552-de84-11e6-9d84-696e51ef4747.png)

## What is the desired behavior?

If GitBook knows what the link is by name when you type, why not fill in that as the friendly name for the link.

I was thinking it was something that the tool would auto-resolve when it built the book, but...

![screen shot 2017-01-19 at 9 45 09 am](https://cloud.githubusercontent.com/assets/952793/22102658/f2bf44dc-de83-11e6-91e4-137fced03960.png)

I think having the option at the time of link insertion to `Use SUMMARY Title` or `Bare URL` would be good.

## Slack Room Response

@nagim Jumping on a call now, so don’t have much time. I think we could very quickly do that in the editor, it make sense to set that as the default text, if no other text is selected when adding a link

It could also be handled via a plugin.

@Soreine tagged as directed in the Slack channel.

## Additional information

GitBook Editor:
    - macOS Sierra
    - GB Desktop 6.5.2
    - AsciiDoc

**Comment by AaronO** [comment]
@jaredmorgs To clarify, this issue has been closed because we merged a pull request fixing the issue. (But since the PR is in a private repo it's not publicly visible)

**Comment by jaredmorgs** [comment]
Great work team. Thanks again.


-- 

Sent from Mobile.

**Comment by nagim** [comment]
It works for me only with Markdown (Jared is also using AsciiDoc, if I remember right).
While we're at the topic, do you think that #130 can be handled as well?

Thanks!

**Comment by jaredmorgs** [comment]
Yep i am using Asciidoc so it would need to work with all supported markup
language that GitBook supports.
-- 

Sent from Mobile.
