### ISSUE TITLE
It doesn't show mathematic equations correctly.

### ISSUE THREAD

**Issue by JerryCao1985** [GitbookIO/feedback#323]
## Category

It is a bug related to GitBook.com, it works fine in editor.

## What is the current behavior?

Mathematic equations are not display properly.
Here is what it shows at the page.
$$tn = t{n-1} + f(t{n-1}) / f'(t{n-1})$$$$tn = t{n-1} + f(t{n-1}) / f'(t{n-1})$$

## What is the desired behavior?

I expect the same thing in the editor. Both client and webpage mode works fine.

## Additional information

MacOS Sierra, version 10.12.2
Google Chrome, Version 55.0.2883.95 (64-bit)
GitBook Editor, 6.5.2

JerryCao1985
https://jerrycao1985.gitbooks.io/hack-an-algorithm/content/sqrtx.html

**Comment by Soreine** [comment]
You need to install the [katex](https://plugins.gitbook.com/plugin/katex), or alternatively [mathjax](https://plugins.gitbook.com/plugin/mathjax) plugins on your book. You can install them by following the instructions, or directly from the Editor, in the menu -> Plugins Store.

We should add a warning about it in the Editor, when we detect the use of math without one of these plugins.

**Comment by JerryCao1985** [comment]
I dont have a plugin store in my menu of gitbook client.
Did I miss anything?
