### ISSUE TITLE
Preview in Editor doesn't preview properly

### ISSUE THREAD

**Issue by orgvueelno** [GitbookIO/feedback#328]
## Category

Bug in gitbook.com Editor

## What is the current behavior?

Breaks are omitted in Preview pane. 

![image](https://cloud.githubusercontent.com/assets/14980884/22247819/95b64606-e233-11e6-9449-ee33ba026f4b.png)

## What is the desired behavior?

In this example, preview pane should show some space where I've put breaks.

**Comment by SamyPesse** [comment]
Thank you for the feedback.

The latest editor is using our new markdown parser. We'll fix this issue and release a fix soon.

BTW, do you know that you don't have to use `<br />` to do soft newline. In markdown, in a paragraph, if the line ends with two spaces, it'll insert a soft newline.

Removing the `<br />` will switch the editor to Document mode, (which has a much better UX). In Document mode, pressing <kbd>Shift+Enter</kbd> will insert a newline in the paragraph (no need to type the two spaces), and <kbd>Enter</kbd> will split the paragraph.

##### Markdown source

```
Interval (period)  [[[ THIS LINE ENDS WITH TWO SPACES ]]
options are Auto, Weekly, Monthly, Quarterly and Yearly
```

##### Result

Interval (period)  
options are Auto, Weekly, Monthly, Quarterly and Yearly

**Comment by orgvueelno** [comment]
I didn't know about the two spaces. Very handy. However my Preview pane doesn't bring up the right results although it may draw a break in the actual html page once I publish.
