### ISSUE TITLE
[Bug] Cannot log in with GitHub

### ISSUE THREAD

**Issue by AlbertZed** [GitbookIO/feedback#334]
## Category
Emergency bug

## What is the current behavior?
Choose sign in with GitHub
Then it will redirect to the page
"401
Unauthorized
An user is already associated to this github account."
This issue just came up today. And I am the only user associated with the account.

## What is the desired behavior?
Log in normally to the web editor

## Additional information
Web editor / Chrome
OS X Sierra

Please look into this.

**Comment by AlbertZed** [comment]
The log in system went back to normal.

**Comment by SamyPesse** [comment]
Yes, we deployed a fix a few minutes ago.
