### ISSUE TITLE
insert image via clipboard

### ISSUE THREAD

**Issue by joreg** [GitbookIO/feedback#345]
## Category
feature request

## What is the desired behavior?

Would it be possible to allow inserting images via the clipboard? At the moment my workflow is severly limited by the fact that i have to create an image file on disk manually before being able to choose it for insertion. 

I often make screenshots which i'd like to insert with just CTRL+V. After pressing the shortcut i'd be asked for a filename and it would be saved next to the file i'm inserting to.

**Comment by saveenr** [comment]
+1 on this. In my case, supporting paste from clipboard would make it much easier for those documents where a user has to be led step-by-step through a user interface. In my case, I have no preference regarding the specific filenames, other than they be stored in a stored in folder separate from the text content.

As a reference here is a site that shows how it is done: https://codepen.io/netsi1964/pen/IoJbg (works in Chrome and Microsoft Edge)

**Comment by joreg** [comment]
also i just noticed that this works perfectly with issues on github that accept any image from the clipboard via ctrl+V!

**Comment by a1528zhang** [comment]
+1, when I want to insert a image, I must do these things:
save image from clipboard to desktop;
click upload button;
find image and double click it;
wait for upload;
and then I can edit my passage again.
we need a image paste function, seriously.

**Comment by AaronO** [comment]
This is implemented in the major new version we've been working on ([beta.gitbook.com](https://beta.gitbook.com/)) along with many other editor improvements (and general product improvements).

It's going public end of January.
