### ISSUE TITLE
Make it obvious to add chapters in TOC (e.g: with buttons)

### ISSUE THREAD

**Issue by AaronO** [GitbookIO/feedback#35]
Right now uses have to right click to insert a new part/chapter. That's not very hard, but since we've got a lot of space in the TOC (with the filetree hidden), I think we should make adding chapters easy and obvious, buttons have the advantage of being very obvious.

Here's a mockup of what it could look like:

### Screenshot with buttons

![screen shot 2016-06-15 at 2 48 51 pm](https://cloud.githubusercontent.com/assets/949223/16080404/f72adb3e-3308-11e6-8447-074491fe3aa8.png)

### Screenshot with smaller buttons

![screen shot 2016-06-15 at 2 51 57 pm](https://cloud.githubusercontent.com/assets/949223/16080412/02b2ff54-3309-11e6-9a09-9ff4728918c5.png)

**Comment by Soreine** [comment]
There is now a button to add an article. But not for every part.
