### ISSUE TITLE
AsciiDoc project issues, book.json error

### ISSUE THREAD

**Issue by aaronbartell** [GitbookIO/feedback#352]
## Category

Bug, editor

## What is the current behavior?

I am trying to use AsciiDoc.  When I follow the directions to rename `README.md` and `SUMMARY.md` to be `README.adoc` and `SUMMARY.adoc` it conveys the error: "Could not load your book. Check your book.json for errors."

This also means it *only* displays the **Files** in the left nav and not also the **Table of contents**.

**Steps to recreate:**

- Create new book
- Rename SUMMARY.md to SUMMARY.adoc

## What is the desired behavior?

Desired behavior is to support Asciidoc.

## Additional information

Happens in both desktop and web editors.

  For the GitBook Editor:
    - Operating System: Mac OSX El Capitan 10.11.6
    - (Web) Browser version: Chrome Version 56.0.2924.87 (64-bit)
    - (Desktop) Version of the Editor: Version 6.6.2
  For GitBook.com:
    - Your username: aaronbartell
    - When possible, the URL of the book: https://www.gitbook.com/book/litmis/pase-intro

**Comment by manngo** [comment]
@aaronbartell I thought it was just me. Similar environment (using MacOS 10.12.3 Sierra), but that shouldn’t affect the web version.
Just when I thought it was safe to use GitBook again. It doesn’t seem to like `asciidoc` very much …

**Comment by Soreine** [comment]
This is fixed in the [Editor v7.0.10](https://www.gitbook.com/editor/releases/stable#7.0.10). The Web Editor will be updated during the day.

**Comment by aaronbartell** [comment]
I upgraded the desktop client and it still says it can't find `README.md`.  Is there a something I should set in `book.json` to declare the "flavor" of content (i.e. markdown vs asciidoc)?

![](https://content.screencast.com/users/AaronBartell/folders/Snagit/media/0a4bd591-935f-426a-b3c8-fd22e4c804d7/2017-03-09_09-25-39.png)
