### ISSUE TITLE
Z-index error in popover notification on create new ebook page

### ISSUE THREAD

**Issue by glauberfc** [GitbookIO/feedback#362]
## Category

Bug in gitbook.com

## What is the current behavior?

When I click in "Notifications" icon the popover appears behind the modal without backdrop component.

![image](https://cloud.githubusercontent.com/assets/15311858/22990277/6dbbf95a-f397-11e6-9ceb-2423aaef1af5.png)

## What is the desired behavior?

The popover should appears in front of the other component.

## Additional information

- Username: glauberfc
- URL: https://www.gitbook.com/new

**Comment by deloorc** [comment]
I'm experiencing the same issue 
![image](https://cloud.githubusercontent.com/assets/12133491/22988087/47cb5e42-f3b1-11e6-90f2-efc7ac34409b.png)
