### ISSUE TITLE
Switch to markdown editing?

### ISSUE THREAD

**Issue by hackhowtofaq** [GitbookIO/feedback#364]
## Category
Feature

How do I switch to markdown editing?

**Comment by SamyPesse** [comment]
There is an action in the bottom right menu:

<img width="470" alt="screen shot 2017-02-17 at 15 52 44" src="https://cloud.githubusercontent.com/assets/845425/23069825/2ca44a7e-f529-11e6-9563-b3ad50eb220e.png">

**Comment by SamyPesse** [comment]
Do you have an issue with the default editing mode (WYSIWYG) ?

**Comment by hackhowtofaq** [comment]
yeap....markdown is faster for me!

**Comment by AaronO** [comment]
@hackhowtofaq You know that you can use markdown shortcuts in the WYSIWYG ?

It understands titles, code blocks, lists, etc ...

**Comment by hackhowtofaq** [comment]
@AaronO ty too

I didn't know that....but I prefer raw mode...
