### ISSUE TITLE
Total Breakdown on 7.0.1 on both the editor and web....

### ISSUE THREAD

**Issue by energyd** [GitbookIO/feedback#366]
## Category

Bug
## What is the current behavior?
click on a sub-chapter, nothing happens, couldn't open

## What is the desired behavior?
open sub chapter

**Comment by AaronO** [comment]
@energyd Could you provide a link to your project ?

Do you see any kind of error dialog or warning ?

**Comment by energyd** [comment]
No warning/error..

It happens in the editor mode only, not the read mode:
https://www.gitbook.com/book/energyd/code/

**Comment by AaronO** [comment]
@energyd Thanks for posting the link, we were able to track down the core issue. We've merged a fix so you should be good as soon as the next release rolls out.
