### ISSUE TITLE
command+c, command+v do not work in editor

### ISSUE THREAD

**Issue by xmtsui** [GitbookIO/feedback#368]
## Category
bug

## What is the current behavior?
copy words using `command c`, but can not use `command v` to paste in editor.

## What is the desired behavior?
`command v` works.

## Additional information
 - editor 7.0.2
 - os 10.11.6

**Comment by LiTiang** [comment]
This feature must be fixed first **PLEASE** !!!!!!

**Comment by LiTiang** [comment]
What a nice working efficiency !!! 

This Bug is solved !!! Thank u guys ~

And the new UI of gitbook is awesome, great work !

**Comment by SamyPesse** [comment]
Thanks :+1:
