### ISSUE TITLE
UI flashes too much when switching from one file to another

### ISSUE THREAD

**Issue by AaronO** [GitbookIO/feedback#37]
When switching from one markdown file, most of the UI flashes, which is quite distracting and unnecessary (toolbar, editing zone, etc ...). We could improve the loading animation when switching from one file to the other to minimize flashing.

### Current behavior

- Display previous content
- Switch to loading
    - Hide toolbar
    - Remove content container (page outline)
    - Disable document mode switch
- Display new content
    - Restore toolbar
    - Restore content container
    - Show new editor

### Expected behavior

- Display previous content
- Show loading indicator in content holder (page outline), keep toolbar, "document mode" switch, etc ...
- Replace loading indicator with new content

**Comment by SamyPesse** [comment]
It's no longer the case with latest releases.
