### ISSUE TITLE
The content of book.json is open to leak

### ISSUE THREAD

**Issue by haodong** [GitbookIO/feedback#370]
## Category
It concerns the design of gitbook. Specifically, the permission of `book.json`.

## What is the current behavior?
All parameters within `book.json` is free to be viewed by anyone in the rendered pages. Therefore any sensitive information is ready to be leaked. It may produce problems like API leak in this issue: https://github.com/1cgonza/gitbook-plugin-iframely/issues/1 .

## What is the desired behavior?
To protect user privacy, the `book.json` should not, also does not necessary, be open.

**Comment by Soreine** [comment]
For private API keys, the current way-to-go is to pass them as environment variables, as done for the [`plugin-algolia`](https://github.com/GitbookIO/plugin-algolia/)
GitBook.com supports setting environment variables in any book's settings. And you can pass the environment variables from the command line:

```shell
$ PRIVATE_KEY="..." gitbook serve
```
