### ISSUE TITLE
Version 7.0.3 Asciidoc not working any more

### ISSUE THREAD

**Issue by manngo** [GitbookIO/feedback#372]
## Category

Big

## What is the current behavior?

- asciidoc no longer previews
- README.asciidoc no longer working. I get the message: `Could not load your book. Check your book.json for errors`. Given that `book.json` is empty indicates that there is a bug somewhere else.

This applies to both the desktop editor and the web version.

## What is the desired behavior?

Working

## Additional information

 For the GitBook Editor:

- MacOS Sierra
- Desktop 7.0.3

For GitBook.com:
- manngo-net
- https://www.gitbook.com/book/manngo-net/advanced-sql/details

**Comment by manngo** [comment]
Apropos Asciidoc

I don’t want to be unduly uncooperative, but I signed up for a paid organisation account last year, hoping to be able to get productive writing with asciidoc. I was especially excited to see a desktop editor which offered wysiwyg support.

To date, asciidoc support has been intermittent, and I abandon it GitBook for a while and come back to it every now and then to see whether I can use it. Sometimes I can, and sometimes I can’t. I then turn to Atom with the Asciidoc plugin, or to Marked 2 with the asciidoc plugin, and work from there. Both products give me more control over the product and work reliably.

I just need to know whether asciidoc will be usable in the near future, or should I try something else? I don’t mean to whinge, but I just need something I can work with.

Thanks

**Comment by stevenzins** [comment]
Recently, I get same message: "Could not load your book. Check your book.json for errors." The online editor preview works for some pages but not others. The website is generated properly. 

The main problems are that the TOC is not available and the Preview is not always available in the editor.

My book.json is valid at jsonlint.com: https://www.gitbook.com/book/stevenzins/uft6/edit#/edit/master/book.json?_k=vcsrcm

{
"plugins": [
"mathjax"
,"ga"
,"collapsible-chapters"
],
"structure": {
"readme": "intro.adoc",
"summary": "SUMMARY.adoc"
},
"variables": {
"qed": "_Q.E.D._",
"pass2": "<a HREF='#abcde'> pass2 to abcde </a>",
"pdfvar": "_PAGENUM_, _TITLE_, _AUTHOR_ and _SECTION_"
},
"pdf": {
"footerTemplate": "_PAGENUM_ - UFT6 gitbook - © 2017 Steven D. Zins "
},
"pluginsConfig": {
"ga": {
"token": "UA-37307380-1"
}
}
}

This is a paid site on the web at uft6.zins.org.
Help, please.
...Steven Zins

**Comment by manngo** [comment]
With respect, why is this issue closed? I have update to 7.0.9, and neither part of the issue is resolved.

- asciidoc preview _still_ doesn’t work
- The book still doesn’t load, and it still complains about `book.json`. The workaround in issue #411 helps, but my understanding is that it is a workaround, and reverting to `summary.asciidoc` breaks again.

**Comment by AaronO** [comment]
@manngo This will be fixed in `7.0.10`. It should be live in ~30mn or so.

(`7.0.9` was shipped 3 days ago, this fix was merged ~2h ago)

**Comment by manngo** [comment]
I have installed 7.0.10

- asciidoc preview still doesn’t work
- I still get the error messages regarding book.json

What actually was fixed to justify closing this issue?

**Comment by manngo** [comment]
Version 7.0.11

Still unfixed. Please re-open issue.

**Comment by manngo** [comment]
The tag says `investigating`, but the issue is still closed. Version7.0.12. __Please reopen this issue__

**Comment by lazaridis-com** [comment]
@AaronO, "This will be fixed" does not mean that you close the issue.

Why don't you listen to @manngo , and reopne the issue?
