### ISSUE TITLE
Version 7.0.3: Can't use the editor offline

### ISSUE THREAD

**Issue by AngelGL** [GitbookIO/feedback#376]
## What is the current behavior?

While trying to update/install the last version (the same error for 7+) I get the following error:
**A javascript error ocurred in the main process**

![chrome_2017-02-20_20-52-40](https://cloud.githubusercontent.com/assets/4478698/23146751/e619369e-f7af-11e6-9386-8a6d9ee81712.png)

Then when I open the editor, I get theses error and still blank:

**Critical error while listing books**

![explorer_2017-02-20_20-58-08](https://cloud.githubusercontent.com/assets/4478698/23146756/f23068d0-f7af-11e6-9dc7-60ec7dac2dd4.png)

It works fine when I'm connected to WiFi

## What is the desired behavior?

Book should be editable offline

## Additional information
  For the GitBook Editor:
    - Windows 7
    - Desktop Version of the Editor: 7.0.3

**Comment by SamyPesse** [comment]
This is going to be fixed in `7.0.4`.

**Comment by AngelGL** [comment]
@SamyPesse The first error have been fixed, but still can't use the editor offline. It looks like the editor is only trying to search for the online library instead of using the local.
![chrome_2017-02-22_11-14-43](https://cloud.githubusercontent.com/assets/4478698/23217813/de016c0a-f8f0-11e6-84ff-b05d675cb2c1.png)

It works fine if I use the 6.6.2 version editor

**Comment by CMagistrado** [comment]
![screen shot 2018-01-16 at 4 19 19 pm](https://user-images.githubusercontent.com/18632928/35018963-0a7cc29e-fad9-11e7-81a6-b6aae5640fcb.png)

- Kept attempted to push, and it asked my username and password, so I entered my GitHub credentials over and over.
- Went online to gitbook, which I originally used my GitHub account to login to. 
- I revoked access via token, then generated a new token (would have plugged it into the app, but it didn't prompt for it or anything).
- Changed Password of gitbook.
- Tried to push gitbook up, didn't work.
- Now getting this error.

**Comment by CMagistrado** [comment]
Same. Pls halp.

**Comment by CMagistrado** [comment]
I have de wae brudda.
Go to **GitBookEditor** > **Logout**.
Now go and re-login with your Github account.

My Steps:
Login to Gitbook. Disconnect all Github account links.
Login to Github. Disconnect all Gitbook links.
(locally) Logout of Gitbook App.
Log in via Github.

Working!
