### ISSUE TITLE
book.json has errors when using 7.x series editors

### ISSUE THREAD

**Issue by jaredmorgs** [GitbookIO/feedback#411]
## Category

This is a bug that concerns the 7.x series of Web and Desktop editors.

## What is the current behavior?

The book.json file shows as having an unidentified parsing error when using the 7.x series Web editor or Desktop editor (mac)

![gitbook-issue](https://cloud.githubusercontent.com/assets/952793/23654466/87beebf6-037c-11e7-9ad2-58e86364e4eb.gif)

## What is the desired behavior?

That the book.json is validated correctly.

That the book.json file does not error when loaded, which was the behaviour in the 6.5.2 editor. 

## Additional information

  For the GitBook Editor:
    - mac0S Latest
    - Chrome for Mac latest
    - 7.x
  For GitBook.com:
    - jaredmorgs
    - https://www.gitbook.com/book/hubpress/hubpress-knowledgebase/details

NOTE: user @nagim in Slack said the following:

nagim [5:40 PM] 
@jaredmorgs Just a tip, I converted *only* my summary from AsciiDoc to MarkDown, renamed it to `SUMMARY.md` and it works with that.

aaron [5:42 PM] 
@jaredmorgs can you post this in feedback and Cc @SamyPesse samypesse and @Soreine  

jaredmorgs [9:15 PM] 
Yep, shall do @aaron I"ll also post @nagim's workaround as well. :thumbsup:

**Comment by manngo** [comment]
I just saw this and @nagim’s workaround. It worked for me. Still can’t preview asciidoc, but at least the book works again. For now …

**Comment by manngo** [comment]
Please see my comment on issue #372. I don’t think this issue has been resolved.

**Comment by Soreine** [comment]
This should be fixed in the [Editor v7.0.10](https://www.gitbook.com/editor/releases/stable#7.0.10). The Web Editor will be updated during the day.

**Comment by AaronO** [comment]
@nagim Imre is your `SUMMARY` in AsciiDoc ? I could imagine `asciidoctor.js` eating up a ton of `ram` on larger documents.

**Comment by nagim** [comment]
@AaronO Yes, it is, I thought I would throw it at the 7.0.10 to see if it works.

**Comment by jaredmorgs** [comment]
What is classed as a "big" summary in this context?

> --

Sent from Mobile.

**Comment by nagim** [comment]
~600 lines in my case. Or maybe the problem is the list levels, I have level 6 deep lists. I will test it with only as deep as level 5.

**Comment by AaronO** [comment]
@jaredmorgs @nagim Could you guys share your `SUMMARY` files ?

See if there's a substantial difference between parsing with `asciidoctor.js` or a similar `SUMMARY` in markdown.

We have very little control over `asciidoctor.js` and since it's `ruby` code transpiled to `JS` using `opal`, I think it's far from optimal, but it would be interesting to test and benchmark both.

**Comment by jaredmorgs** [comment]
OK that is a colossal book. The files I'm dealing with are way smaller.

https://www.gitbook.com/book/hubpress/hubpress-knowledgebase/edit#/edit/master/SUMMARY.adoc?_k=73u4as

-- 

Sent from Mobile.

**Comment by nagim** [comment]
@AaronO I guess they have made that more efficient in newer versions (it no longer uses Ruby I think, but @Mogztter could confirm). I will share my summary on a private channel.

**Comment by nagim** [comment]
Update: the size was the problem. I trimmed it down to about 250-260 lines. It took about a minute to load it, but it loaded eventually. Level 6 deep list items are also not a problem (it was an issue before, so :+1: for solving that). I will experiment further to find out the treshold.

**Comment by Mogztter** [comment]
@nagim 600 lines shouldn't be a problem. How can I reproduce this issue ? Are you using the latest version of Asciidoctor.js ?

**Comment by nagim** [comment]
@mogztter I'm using whatever GitBook Editor 7.0.10 is using :smile:

**Comment by nagim** [comment]
It took 7 minutes to load it with 400 lines. Around the same time for ~470 lines. 500 lines in 11 minutes seems to be the limit (it fails to load with 520).

**Comment by Mogztter** [comment]
Could you share your `SUMMARY` file ? Did you try to preview the same file in Atom ? 
Is the code of GitBook Editor open source ?

**Comment by nagim** [comment]
Yes, I can preview it in Atom just fine in a couple of seconds. The Editor's code is not public I think.

**Comment by jaredmorgs** [comment]
I think that would suggest that some tooling optimisation on the GitBook
side may need to occur over time.

I know that this is an iterative process, so thanks for looking into it,
team.

> --

Sent from Mobile.

**Comment by manngo** [comment]
So, why is this issue closed, if users are still reporting problems. It certainly hasn’t been resolved for me.
