### ISSUE TITLE
Uncaught TypeError after uploading to GitBook but not locally  

### ISSUE THREAD

**Issue by Mackiovello** [GitbookIO/feedback#423]
## Category

Bug with the uploading or build

## What is the current behavior?

One of [my pages](https://docs.starcounter.io/guides/web-apps/using-web-components/) hits the following error in `theme.js:1`:

```
Uncaught TypeError: Cannot read property 'removeChild' of null
    at n (theme.js:1)
    at A (theme.js:1)
    at de.fn.init.replaceWith (theme.js:2)
    at Object.success (theme.js:4)
    at l (theme.js:2)
    at Object.fireWith [as resolveWith] (theme.js:2)
    at r (theme.js:3)
    at XMLHttpRequest.<anonymous> (theme.js:3)
```

This causes some plugins to fail and the custom CSS to partly fail.

The weird thing is that this only happens after it's uploaded. When running with `gitbook serve` it works perfectly.

## Additional information

Applies to, at least, Firefox and Chrome. Gitbook CLI version 2.3.0. Gitbook version: 3.2.2.

**Comment by Mackiovello** [comment]
This commit https://github.com/Starcounter/Docs/commit/d551a8358ec6917c3f4d1b43d62c7d9c4dc69ef1 fixed the problem for me. I think it might be from `target=_blank`

**Comment by AaronO** [comment]
@Mackiovello Don't you have a custom theme ? Could you check if you have any calls to `.removeChild(` ?

**Comment by Mackiovello** [comment]
> @Mackiovello Don't you have a custom theme ? Could you check if you have any calls to .removeChild( ?

No, I don't use a custom theme only custom CSS and template extension. The only occurrences of `.removeChild` are in `_book\gitbook` and `_book\theme.js`.

**Comment by Mackiovello** [comment]
Closing as no longer relevant
