### ISSUE TITLE
Markdown Stuck

### ISSUE THREAD

**Issue by enewmanMN** [GitbookIO/feedback#427]
## Category

Bug?

## What is the current behavior?

I entered the markdown editor on the Desktop version of GitBook Editor and it now has the 'Edit Markdown' toggle option grayed out so I can't go back to the regular editor view for this section. It is only happening to this one section out of the thirteen I have in this particular repository so I'm rather frustrated.

## What is the desired behavior?

I should be able to use the 'Edit Markdown' toggle... 

## Additional information

I'm running on a Windows operating system with the latest Gitbook Editor installed as a desktop application. I've been using it without any error for a few weeks now and now all of a sudden I can't get out of the markup view of my section...

**Comment by enewmanMN** [comment]
It also is stuck in markdown on the Gitbook Editor available as a web application.

**Comment by AaronO** [comment]
@enewmanMN The editor fallbacks to "raw mode" (markdown mode) if your page contains custom HTML or uses the template syntax. Those are not yet supported in document mode (but will at some point)

**Comment by enewmanMN** [comment]
Okay I will look for that thank you!
