### ISSUE TITLE
plugins.gitbook.com doesn't display any plugins

### ISSUE THREAD

**Issue by Mackiovello** [GitbookIO/feedback#428]
## Category

Bug at plugins.gitbook.com

## What is the current behavior?

[plugins.gitbook.com](https://plugins.gitbook.com/) doesn't display any plugins. Refreshing the page doesn't fix it. Nothing is logged to the console.

Seems to be something wrong on the server side

![capture](https://cloud.githubusercontent.com/assets/19392292/23946513/f28f7ce4-097a-11e7-82c2-b5354431a366.PNG)

## Additional information

Google chrome 56.0.2924.87 (Official Build) (64-bit)

Same issue on Firefox.

**Comment by Mackiovello** [comment]
Down again today.

**Comment by lazaridis-com** [comment]
@Mackiovello , is this about `the plugins not displaying`, or additionally about `the plugins not functioning`? Please clarify.

@AaronO, "Mackiovello opened this Issue 13 days ago "

**Comment by Mackiovello** [comment]
> @Mackiovello , is this about the plugins not displaying, or additionally about the plugins not functioning? Please clarify.

The issue is exactly as described above: I go to https://plugins.gitbook.com/ and nothing is displayed. It's happing right now again: 
![noplugins](https://cloud.githubusercontent.com/assets/19392292/24403968/8af73ca8-13bf-11e7-9436-30d6925bd53a.PNG)
![exception](https://cloud.githubusercontent.com/assets/19392292/24403969/8c7062bc-13bf-11e7-9fc5-93b894bbd5b8.PNG)
![network](https://cloud.githubusercontent.com/assets/19392292/24403971/8e2aed8e-13bf-11e7-93c9-e66e534bde0a.PNG)

**Comment by lazaridis-com** [comment]
to me it just looks that it's intentionally disabled. If so, then a text should inform about this.

**Comment by lazaridis-com** [comment]
@AaronO , @SamyPesse you simply cannot leave such an issue without a comment.

**Comment by Mackiovello** [comment]
Hit this one again today. Do we have any updates?

**Comment by hellt** [comment]
Experiencing the same problem on all browsers/platform as well

**Comment by brentbenton** [comment]
New community member here, kinda stymied by this issue.  Doesn't look good to newcomers who may believe that there really are 0 plugins, or that it isn't a big issue that all the plugin authors contributions to this community are hidden/inaccessible.

**Comment by Mackiovello** [comment]
> New community member here, kinda stymied by this issue. Doesn't look good to newcomers who may believe that there really are 0 plugins, or that it isn't a big issue that all the plugin authors contributions to this community are hidden/inaccessible.

@AaronO Could it please be possible to get a response on this one? It's clearly not only a minor issue.

**Comment by duncanyb** [comment]
Strange thing is that sometimes it does seem to work... but most of the time it doesn't

**Comment by Mackiovello** [comment]
> Strange thing is that sometimes it does seem to work... but most of the time it doesn't

Yes, it's super inconsistent. I'll try to ask the GitBook people to fix this is as soon as possible.

**Comment by AaronO** [comment]
@Mackiovello @duncanyb Taking a look at it now. I think NPM made some changes on their server end that made our method of obtaining the package list unstable.

We did replace it with a PR that also turns `plugins.gitbook.com` into an API (moving the end-user ui to `www.gitbook.com`).

That PR was on hold with all the work on our new product release, so I'm going to see if I can extract the package fetching logic from the new PR and merge it into master (without stripping the UI).

**Comment by AaronO** [comment]
@duncanyb Out of curiosity I would love to know which plugins you're using or looking to use.

With our next product release we're considering shipping high-quality 1st party implementations of the most common/popular/useful plugin features.

**Comment by Mackiovello** [comment]
It seems to have been fixed now. Thank you!

Closing

**Comment by AaronO** [comment]
@Mackiovello @duncanyb Just wrote some of the ugliest code that I've written in a long time, committed a few sins in the process, but it works, should be faster and more reliable too.

https://plugins.gitbook.com/

**Comment by duncanyb** [comment]
I use Image Captions... But was looking at the plugin section for some of the work around theming.

**Comment by AaronO** [comment]
@duncanyb Image Captions is now a builtin feature in our new release (in Beta). What kind of theming or changes are you looking to make ?

**Comment by duncanyb** [comment]
Not sure, a header and potentially an advert column. Went from selling my book via amazon.com etc to putting it up on gitbook / github. Would be nice to have some form of monetization. Now it feels the "views" just disappear in a vacuum.
