### ISSUE TITLE
Settings page has broken layout on smaller screens 

### ISSUE THREAD

**Issue by Mackiovello** [GitbookIO/feedback#435]
## Category

Bug on setting page `https://www.gitbook.com/book/<organization>/<book>/settings`

## What is the current behavior?

On screens smaller than 970px in width, the settings tab overlaps the rest of the page.

![badscrolling](https://cloud.githubusercontent.com/assets/19392292/23992445/44c6899a-0a3d-11e7-9882-a3805b3ea713.gif)

## Desired behavior

It should either be stuck to the top of the page or floating clearly over the other elements.

## Additional information

Is an issue on both chrome and firefox

**Comment by lazaridis-com** [comment]
@AaronO , I experienced this problem, too. The minimal action here is: set priority to "highest".

**Comment by lazaridis-com** [comment]
Quick solution would be to set the width to 1000px, in a way that a bottom scroll-bar comes up, when the user resizes below 1000px (similar to the github ui).

**Comment by Mackiovello** [comment]
This one is easy to fix by increasing the z-index of the div with the `sticky` class and removing the margin between the save button and the menu.
CC @Soreine

**Comment by Mackiovello** [comment]
Closing as no longer relevant
