### ISSUE TITLE
Editor - multi tabbed view

### ISSUE THREAD

**Issue by nagim** [GitbookIO/feedback#44]
Hi,

Working on multiple files parallel is a common use case.
We could open each file in a new tab.

Cheers,
Imre

**Comment by SamyPesse** [comment]
Since the last editor (Version 6) no longer requires the user to save a file before switching to another one, I don't think this feature request makes sense anymore.

@nagim do you agree?

**Comment by nagim** [comment]
Thanks for following up @SamyPesse.
It can be closed now. The editor performance became much better so it's not that big deal jumping between the files.
