### ISSUE TITLE
Preview is not rendering when editing in markdown

### ISSUE THREAD

**Issue by benyohaiphysics** [GitbookIO/feedback#441]
## Category

Bug
GitBook.com

## What is the current behavior?
When editing in markdown, the preview pane does not show anything.

## What is the desired behavior?

The markdown should be rendered.

## Additional information

benyohaiphysics
https://www.gitbook.com/book/benyohaiphysics/aqa-9-1-physics/edit#/edit/master/README.md?_k=k54a08

**Comment by benyohaiphysics** [comment]
![untitled](https://cloud.githubusercontent.com/assets/24621797/24100484/5eefde7a-0d6c-11e7-9596-266d9f5c3ec0.png)

**Comment by AaronO** [comment]
@benyohaiphysics this seems to work for me

### Document Mode

![image](https://cloud.githubusercontent.com/assets/949223/24397858/cacd3304-13a7-11e7-8711-6dcadd34b580.png)

### Raw Mode

![image](https://cloud.githubusercontent.com/assets/949223/24397834/b541b118-13a7-11e7-96e0-72580dbed811.png)
