### ISSUE TITLE
Variables are not resolved in SUMMARY.md or GLOSSARY.md

### ISSUE THREAD

**Issue by cdrfun** [GitbookIO/feedback#444]
## Category
Bug 
Gitbooks.com
gitbook-cli

## What is the current behavior?
Variables are not resolved when used in GLOSSARY.md or SUMMARY.md

## What is the desired behavior?
Variables shall be resolved in index, page title and glossary tooltip.

## Additional information
Example on GitBooks.com: https://cdrfun.gitbooks.io/gitbook-bug-demos/
Example on GitHub: https://github.com/cdrfun/gitbook-bug-demos

**Comment by AaronO** [comment]
@cdrfun I don't think we will ever support variables in the `SUMMARY.md` it would be too much of a burden and render the `SUMMARY.md` "unpredictable" (how would it be parsed/rendered/edited by the editor ?)

The `GLOSSARY.md` should take variables into account.

**Comment by AaronO** [comment]
@cdrfun Do you want to close this issue and open one specifically regarding the `GLOSSARY.md` ?

**Comment by cdrfun** [comment]
Sure, I've created #453 
I think it would be good the mention the restriction in the docs, though. I can't find the toolchain docs here at githb or at gitbooks.

**Comment by cdrfun** [comment]
@AaronO  Sure, I've created #453 and created a pull request (https://github.com/GitbookIO/gitbook/pull/1765)
