### ISSUE TITLE
Gitbook.com traffic tab is not displaying data.

### ISSUE THREAD

**Issue by rmoyano** [GitbookIO/feedback#447]
## Category

 Bug in gitbook.com.
## What is the current behavior?

  When you open a *Book* and click on *Traffic*, is not showing the stats.
## What is the desired behavior?

  Display *Traffic* stats.

**Comment by AaronO** [comment]
@rmoyano Can you share your project's URL ?

(Please try and provide the maximum context possible when submitting issues)

**Comment by rmoyano** [comment]
Aaron I've entered now and it's displaying the charts and visits stats. When I created the ticket, I tried with three books:
https://www.gitbook.com/book/rmoyano/ssh-for-everyone/traffic
https://www.gitbook.com/book/rmoyano/lasrecetasdelabuela/traffic
https://www.gitbook.com/book/rmoyano/paradigmas/traffic

It looks like it was a production issue or maybe they made rollback with some version.

Thanks for your time.

**Comment by AaronO** [comment]
@rmoyano Yep, I deployed a fix earlier today soon after my comment.

The error was due to our SSL cert renewals, so it's all good now and we've setup automated cert renewal :)

**Comment by rmoyano** [comment]
Thanks Aaron!
