### ISSUE TITLE
404 error, page not found

### ISSUE THREAD

**Issue by abo321** [GitbookIO/feedback#448]
## Category

https://www.gitbook.com/read/book/abo321/mykb
shows

404
Not Found
This book has not been published yet

## What is the current behavior?

1. I created a KB book named 'mykb' and created some articles
2. Deleted this book 'mykb' and related files
3. Re-create a KB book named 'MyKB' and created some articles
4. Seems the publish failed and cannot read it

The build log,

> Downloading source
> Pulling from S3
> Extracting source
> tar: .gitignore: time stamp 2017-03-23 07:54:13 is 101.799801846 s in the future
> tar: README.md: time stamp 2017-03-23 07:54:13 is 101.799590094 s in the future
> tar: SUMMARY.md: time stamp 2017-03-23 07:54:13 is 101.799534303 s in the future
> tar: book.json: time stamp 2017-03-23 07:54:13 is 101.799491599 s in the future
> tar: check-disk.md: time stamp 2017-03-23 07:54:13 is 101.79944348 s in the future
> tar: check-network.md: time stamp 2017-03-23 07:54:13 is 101.799394825 s in the future
> tar: first-question.md: time stamp 2017-03-23 07:54:13 is 101.799347222 s in the future
> tar: second-question.md: time stamp 2017-03-23 07:54:13 is 101.799299244 s in the future
> GitBook version is 3.2.2
> Tweaking book.json
> Installing plugins
> info: installing 2 plugins using npm@3.9.2 
> info:  
> info: installing plugin "theme-faq" 
> info: install plugin "theme-faq" (*) from NPM with version 1.2.1 
> /tmp/book
> └── gitbook-plugin-theme-faq@1.2.1 
> 
> info: >> plugin "theme-faq" installed with success 
> info:  
> info: installing plugin "comment" 
> info: install plugin "comment" (*) from NPM with version 1.0.5 
> /tmp/book
> ├── gitbook-plugin-comment@1.0.5 
> └── gitbook-plugin-theme-faq@1.2.1 
> 
> info: >> plugin "comment" installed with success 
> Building Site, will upload
> info: 9 plugins are installed 
> info: 8 explicitly listed 
> info: loading plugin "comment"... OK 
> info: loading plugin "highlight"... OK 
> info: loading plugin "search"... OK 
> info: loading plugin "lunr"... OK 
> info: loading plugin "sharing"... OK 
> info: loading plugin "fontsettings"... OK 
> info: loading plugin "theme-faq"... OK 
> info: loading plugin "theme-default"... OK 
> info: found 5 pages 
> info: found 1 asset files 
> error: error while generating page "README.md": 
> 
> Template render error: (/root/.gitbook/versions/3.2.2/node_modules/gitbook-plugin-search/_layouts/website/page.html)
>   TypeError: Path must be a string. Received undefined

## What is the desired behavior?

I would expect to read the book 'MyKB'

Thanks so much for your great support!

**Comment by AaronO** [comment]
@abo321 Closing this issue because the book no longer exists (it looks like you created an alternative).

**Comment by abo321** [comment]
Thanks! Closed it.
