### ISSUE TITLE
can't use handlebars.js code

### ISSUE THREAD

**Issue by kimnaam** [GitbookIO/feedback#456]
when type the code of "handlebars.js", the editor will be broken.

ex: **{{#each .}}**

**Comment by Mackiovello** [comment]
This is documented here: https://toolchain.gitbook.com/templating/#escaping

Just put `{% raw %} {% endraw%}` around the block of code

**Comment by Mackiovello** [comment]
@AaronO I would consider closing this issue as answered

**Comment by AaronO** [comment]
@Mackiovello Closing, thanks
