### ISSUE TITLE
Generate HTML Pages without them being listed in ToC?

### ISSUE THREAD

**Issue by latenitefilms** [GitbookIO/feedback#467]
## Category

Bug

## What is the current behavior?

The internal links at https://dev.commandpost.io/hs/ don't seem to work. It looks like it causes a JavaScript error (`Error: Syntax error, unrecognized expression:`)?

## What is the desired behavior?

Clicking the internal links should open the correct pages.

## Additional information

Tried on both Safari & Chrome on a Mac.

**Comment by latenitefilms** [comment]
I've only just worked out that `html` will only be generated for items listed in the table of contents.

Is there anyway for GitBook to generate `html` files without having the files listed in the table of contents?

**Comment by Mackiovello** [comment]
I agree on this one! This should certainly be possible.

**Comment by Mackiovello** [comment]
Worth noting is that it's possible if you create HTML pages and link to them, but not markdown files that have to be parsed to HTML

**Comment by latenitefilms** [comment]
Good to know, thanks @Mackiovello.
