### ISSUE TITLE
I cannot edit my book!

### ISSUE THREAD

**Issue by KorJeongHyeonLee** [GitbookIO/feedback#471]
## Category

bug , GitBook.com
## What is the current behavior?
From the moment I try to edit my books, it does not work. If I click on the edit button for a book, as you can see, it just comes up with a blank screen. Also, when I try to click the setting tab, the Application Error page appears. plz help me ...

 
## What is the desired behavior?
The Editor page should appear.

## Additional information

- OS = OS X El Capitan
- Browser = chorme (This is the current version.)

![2017-04-12 4 20   ##21](https://cloud.githubusercontent.com/assets/20096812/24945898/02162aaa-1f9c-11e7-9a72-2955cda49aac.png)

**Comment by changkun** [comment]
Same problem to me an hour ago, but fixed right now. I suppose that they were maintaining the online edit function.

**Comment by KorJeongHyeonLee** [comment]
It was really fixed ...

**Comment by AaronO** [comment]
@changkun @KorJeongHyeonLee Our git servers experienced an extremely high load of requests last night which caused some downtime, since the editor uses APIs provided by our git server to load and commit data.

Sorry for the inconvenience, just wanted to provide some insight to clarify.
