### ISSUE TITLE
No book.json created

### ISSUE THREAD

**Issue by rohan-deshpande** [GitbookIO/feedback#475]
## Category
Possible bug

## What is the current behavior?
Started gitbook from existing github repo, didn't get a `book.json`

## What is the desired behavior?
I think I should get a `book.json`?

## Additional information
Am I supposed to create one? Is there some default template somewhere? I am guessing it needs to be done in order to configure my book but I assumed it would get create in the root directory of the repo when I connected it.

**Comment by Mackiovello** [comment]
As documented [in the documentation](https://toolchain.gitbook.com/structure.html), `book.json` is optional. It's also documented how to configure here: https://toolchain.gitbook.com/config.html

**Comment by rohan-deshpande** [comment]
Ah okay my bad. Closing.
