### ISSUE TITLE
Unexpected HTTP status code: 500

### ISSUE THREAD

**Issue by cborodescu** [GitbookIO/feedback#478]
## What is the current behavior?

I've just created a new account, changed my username and I'm now unable to edit the Books I've created because of the 500 HTTP error I get in the Mac app. 

## Additional information
Here's the screenshot: https://snag.gy/KlghnC.jpg

**Comment by AaronO** [comment]
@cborodescu Since you're using the desktop editor. If you logged in before changing your username, you'll need to logout and relogin with the new username. Because the old username/auth is no longer valid.

I'll see if we can improve the error message we return, rather than a 500.

**Comment by cborodescu** [comment]
Nope, same error. Now, I'm trying to remove the books from Chrome and it gives me the same error. I would like to delete/remove my entire account and try again, but I can't delete it because it says that I have to delete the books first - which I can't :(

**Comment by cborodescu** [comment]
Hey @AaronO can somebody help me with this?

**Comment by AaronO** [comment]
@cborodescu What are your usernames ?

**Comment by cborodescu** [comment]
@AaronO Changed it from "cborodescu" to "appticles"

**Comment by AaronO** [comment]
@cborodescu Do you want me to remove your pre-existing books ?

Could you list the steps you made ? The git repos attached to your books appear empty and invalid. How did you create those projects ? Did you force push any local repos to them ? Anything noteworthy ? (trying to understand the core issue here)

**Comment by cborodescu** [comment]
@AaronO yes, please. 

I logged in with GitHub, added those book titles, then changed the username. I didn't use the option to sync it with GitHub. And what's strange is that I had at one point 3 books and all of the sudden, after installing the Mac editor, one of those books simply vanished. 

It was really odd ...

**Comment by AaronO** [comment]
Is there anything else you can remember ? I feel like something must have went wrong whilst renaming your account, but I'm going to have to dig into our logs to see what.

As a side note, we do recommend teams/companies user organisation accounts (rather than single user accounts).

**Comment by AaronO** [comment]
@cborodescu Did you ever edit/push any of your content ?

**Comment by AaronO** [comment]
@cborodescu I have successfully removed the invalid projects on your profile

**Comment by cborodescu** [comment]
@AaronO thanks. No I didn't get to push/edit anything. In fact, it was not working and that's the reason I installed the Mac editor.

**Comment by AaronO** [comment]
@cborodescu From our logs, it appears `cborodescu/frequently-asked-questions` was removed ~1h30 after renaming your account.

**Comment by cborodescu** [comment]
Yup, everything works now. Thanks, really appreciate the help.

**Comment by AaronO** [comment]
@cborodescu How did you create your projects ? Did you import them from a bare GitHub repo ?

**Comment by cborodescu** [comment]
Nope, just from your dashboard.

**Comment by cborodescu** [comment]
Can I remove my account? If I do I guess you'll still have the logs, right?

**Comment by AaronO** [comment]
@cborodescu Yes, we'll still have the logs, so you can remove your account. Sorry for the error you encountered that's definitely a strange one, I'm going to dig into it.

**Comment by cborodescu** [comment]
@AaronO this is incredibly frustrating. I've removed my account, created a new one and an organization and now everything is frozen out ...

<img width="1278" alt="screen shot 2017-04-24 at 6 37 19 pm" src="https://cloud.githubusercontent.com/assets/917862/25345298/60a15ce0-291d-11e7-811e-ceda427a80af.png">

I received the e-mail and confirmed, but still nothing ...

**Comment by cborodescu** [comment]
@AaronO and by the way, I cleared my cache, cookies and also tried it with Incognito. Still the same. Maybe you can help with resetting the token or something ...

**Comment by AaronO** [comment]
@cborodescu There's something really strange about the number of issues you're encountering. A member of our team logged into your account (using our admin dashboard) and everything worked smoothly.

Do you have the Grammarly plugin in Incognito mode too ?

Another user reported Grammarly causing lots of issues in the editor and co. (I believe their plugin messes with the DOM and our app doesn't like that).

Could you try disabling Grammarly, restarting your browser and trying the same page ?

**Comment by AaronO** [comment]
@cborodescu Can you try in firefox / Safari or some other browser with no plugins? (I want to see if your plugins injecting things into our pages are the source of the issue)

**Comment by cborodescu** [comment]
@AaronO I don't have Grammarly. I have tried on Safari on my Mac, on one of my colleague's Mac (Chrome, Safari and Firefox) ... still the same error in console: "invalid or unexpected token". 

I think there's an issue with the e-mail validation ... I only got this error after I validated it.

**Comment by AaronO** [comment]
@cborodescu We've fixed it manually. In your descriptions (org & user) you had two "line break" unicode characters (`8232` / `0x2028`), those break the JSON/JS parsing done by the browser, thus breaking our frontend JS code (neither of those characters are escaped by default in JS).

We'll escape those characters moving forward in a upcoming deployment.

Where did you pull those descriptions from, did you copy paste them from Word or some other program ?

**Comment by cborodescu** [comment]
@AaronO thanks for the patience with this. It works now. I think it was a .page file.

**Comment by AaronO** [comment]
No problem, I'm happy we found the core issue :) That was pretty obscure and annoying to debug.
