### ISSUE TITLE
YAML Frontmatter edition

### ISSUE THREAD

**Issue by SamyPesse** [GitbookIO/feedback#5]
### Current situation

Plugins and themes (like [API docs](https://github.com/GitbookIO/theme-api) or [FAQ](https://github.com/GitbookIO/theme-faq)) are using the YAML frontmatter:

```
---
related:
    - some/other/page.md
    - another_related_article.md
---

My article!
```

But the editor is currently parsing it, then corrupt it during save.

### Suggestion

The front matter should be shown as an editable table (similar to GitHub) on top of the content.

**Comment by AaronO** [comment]
@SamyPesse Isn't this implemented in `6.0.0-alpha.3` ?
