### ISSUE TITLE
Gittbook is not supporting Grammarly.

### ISSUE THREAD

**Issue by vineetsagar7** [GitbookIO/feedback#502]

**Comment by Mackiovello** [comment]
Wait, how does this work? Where is it not supported? Is it with input fields in your GitBook or in the editor?

**Comment by vineetsagar7** [comment]
If I do any spelling mistakes it won't correct it, instead it sends the cursor to the first line of the paragraph and GitBook's editor won't let me write until I correct it.

**Comment by Mackiovello** [comment]
Got it, so it should work like it does in GitHub. This would be fixed if Grammarly would work in editors such as Atom and VS Code.

**Comment by AaronO** [comment]
@vineetsagar7 @Mackiovello Yeah, Grammarly works fine in plain `<textarea>`s but breaks other more complex editors like ours because it modifies the DOM which conflicts with the editor.

They are working on making Grammarly more "react friendly" so it doesn't break rich editors.

**Comment by AkashGutha** [comment]
@AaronO is there any update on their `working on making Grammarly making react-friendly`?

**Comment by AaronO** [comment]
@AkashGutha No update from Grammarly that I'm aware of, will check with the team on Monday.

However we do disable Grammarly in the new release (https://beta.gitbook.com) to avoid conflicts/bugs and will re-enable it when we know that Grammarly has improved their "react compatibility".
