### ISSUE TITLE
Version 6.0 on Mac - Editor No longer usable

### ISSUE THREAD

**Issue by chrismalek** [GitbookIO/feedback#52]
I really love gitbook. I just want to start out with that so I don't sound too negative here.

I just updated OSX to version 6.0. It is not usable:

* No way to remove the preview pane and just write in MD.
* I am having a real problem editing the straight markdown. I will put my cursor on the raw text document and the cursor gets moved. I am guessing by the code doing the preview (which I can't disable).
* There is also these errors keep popping up.
![2016-07-11_10-58-22](https://cloud.githubusercontent.com/assets/9403/16741044/7125c262-4756-11e6-8c7a-12240134b403.png)

* Use the tab key in the MD editor no longer does what it should do (insert a tab). Instead it moves to the preview pane often showing the error from above. 

I am still going through the editor looking for other items

**Comment by SamyPesse** [comment]
Thank you again for your feedback 👍 🍻 

1. I'll add an option to hide the preview panel
2. Are you talking about the document mode ("Word/Google Doc" mode) or the raw mode (pure markdown)?
3. Working on it 👷 Can you send me a markdown snippet causing this?
4. Working on it 👷 

You can expect a new release in the coming days that will fix most of these issues.

**Comment by chrismalek** [comment]
for (2) I am talking about raw model. Here is a screenshot for clarity.
![2016-07-11_15-18-55](https://cloud.githubusercontent.com/assets/9403/16748792/1178e86a-477b-11e6-844d-54ad5ed712dc.png)


#54 mentions lists not rendering. Here is one example (really horizontal screenshot). This used to render fine pre-version six. The bullets and sub-bullets are no longer rendering here.
![2016-07-11_15-15-26](https://cloud.githubusercontent.com/assets/9403/16748716/a9c00dc0-477a-11e6-908f-c26c1b665c86.png)

I am trying to reproduce (3) to give you some MD to reproduce it.
