### ISSUE TITLE
Version 6- Mac - No Increase Indent ICON in new editor

### ISSUE THREAD

**Issue by chrismalek** [GitbookIO/feedback#53]
There is a decrease indent but not increase indent. TAB does not work.

**Comment by SamyPesse** [comment]
Thank you for the feedback.

What do you need the increase indent for? Increase indent in a list ? or indent a blockquote?

For lists, you can use `Cmd+]` and `Cmd+[` (or `Ctrl+]` and `Ctrl+[` on Windows/Linux).
But I agree, we can add an icon for this or/and bind `Tab` to indent.

**Comment by chrismalek** [comment]
I was trying to indent a list and it would not work. I am 99% sure this worked prior to 6.0 as I never use the control+ options for this. It is not part of my mental model.

**Comment by Soreine** [comment]
We implemented the TAB shortcut. We haven't added a _Increase indent_ button because it is synonym of the _List_ button and such.
