### ISSUE TITLE
Lots of formatting issues in v6

### ISSUE THREAD

**Issue by gnomeontherun** [GitbookIO/feedback#54]
I just updated and am having a lot of issues with the new editor. I like the visual changes, but functionally its very buggy. Here are a few of the big issues I'm having.

* I think the new 'document' mode with auto-formatting is causing a lot of unexpected results as you type, such as new lines are added arbitrarily. 
* The preview in the markdown|preview view doesn't render list items correctly.
* The cursor in the markdown panel doesn't always appear where I click.
* I copy/pasted some markdown into the markdown panel, and all newline formatting was broken.

**Comment by SamyPesse** [comment]
Thank you for the feedback, we are working hard on improving the editor.

1. Can you give me more details to reproduce `new lines are added arbitrarily` ?
2. Can you provide me a snippet for `The preview in the markdown|preview view doesn't render list items correctly.`
3. Working on it 👷 
4. Working on it 👷

**Comment by Soreine** [comment]
Issues that were not fixed are moved to individual issues.

**Comment by bezhermoso** [comment]
To everyone that is experiencing this issue when pasting Markdown content from your clipboard:

I found that the correct newline formatting is preserved if you paste via `Right click > Paste`.

**Comment by Soreine** [comment]
@bezhermoso @gnomeontherun 
Do you still have the copy/pasting issue with version 6.0.2 ? If yes, could you send me an example of Markdown that breaks when pasted ?

**Comment by bezhermoso** [comment]
@Soreine Yep.

Here is a snippet that breaks:

> start snippet

Here is a high-level tree-view of the file structure of the project:

```bash
/<project_root>
├── Vagrantfile
├── Makefile
├── .platform/ # Platform.sh high-level configuration
│   └── routes.yaml
├── bin/ # Executables that are used within the development workflows.
│   ├── drupal*
│   ├── drush*
│   └── sync-host*
├── docker-compose.yml # Defines the relationships and run-time properties of the Docker containers.
├── environment # File containing environment variables
├── src/ # The drupal-project root
│   ├── .gitignore
│   ├── .platform.app.yaml # Platform.sh app route configuration
│   ├── Dockerfile
│   ├── LICENSE
│   ├── bin/ # Some executables installed in the containers for proper pass-through of DrupalConsole and Drush commands.
│   │   ├── drupal-portal*
│   │   └── drush-portal*
│   ├── composer.json
│   ├── composer.lock
│   ├── custom/
│   ├── phpunit.xml.dist
│   ├── scripts/
│   ├── vendor/
│   └── web/ # the Drupal 8 root -- the directory exposed by the web-server.
└── zsh/ # Some zsh configurations
    ├── zshrc
    ├── async.zsh
    └── pure.zsh
```

> end snippet
