### ISSUE TITLE
Version 6 OS X — AsciiDoc not working

### ISSUE THREAD

**Issue by manngo** [GitbookIO/feedback#55]
I have just updated to GitBook Editor 6, and find that I cannot edit or preview any of my asciidoc files. This poses a problem, since all of my files are asciidoc.

Meanwhile I will revert to version 5.5

**Comment by nagim** [comment]
The preview mode is returned in v6.0.1., thanks :+1: :beer: 
However, in this mode, the History Bar doesn't show, Revision History shows only the diff between 2 branches (not the history of the file).

It would be nice if the basic features could be added back in case of asciidoc: syntax highlighting, basic UI elements for editing (formatting, insert link, image, etc.), inserting links of articles in an easy way (drag-and-drop, assets manager, context menu, etc.).

Also, summary list rendering is off in case of asciidoc, see #47.

Thanks,
Imre

**Comment by nagim** [comment]
Also, in the preview, in case of tables, the `[options="header"]` attribute is not displayed properly:

![image](https://cloud.githubusercontent.com/assets/16205115/16767361/529d7a08-483f-11e6-943f-5bf59c978e16.png)
