### ISSUE TITLE
Account has been suspended

### ISSUE THREAD

**Issue by melkikh** [GitbookIO/feedback#574]
## Category

bug
> Your account has been suspended

via login form.
GitBook.com

## What is the current behavior?

1. I registered using github account
2. I changed email in settings
3. I could not login via github
4. After the password was reset (via email), my account was suspended. 

@melkikh

**Comment by AaronO** [comment]
@melkikh I've manually unlocked your account. What was your email prior to changing it ?

**Comment by melkikh** [comment]
@AaronO I already logged in. Thanks
