### ISSUE TITLE
online editor takes several seconds to render one of my pages

### ISSUE THREAD

**Issue by nictuku** [GitbookIO/feedback#581]
## Category

Poor performance of the Editor

## What is the current behavior?

I copy-pasted a file into the GitBook editor and it's freaking out. It's not even a very large page. It has a table in it, but that's OK.

But it takes several seconds to render the page, and sometimes it doesn't even do that.

## What is the desired behavior?

Loading a page should be instant.

## Additional information

 - OSX
- Chrome 62.0.3202.94 (Official Build) (64-bit)
- Grammarly was messing with the edit but I have disabled it for GitBook.

The page is at: https://www.gitbook.com/book/nictuku/microclusters-user-guide/edit#/edit/master/how_does_it_work.md

but it could be renamed soon since I'll try to find a mitigation for it.

**Comment by nictuku** [comment]
i don't know if it's related or not, but the Editor keeps recreating a chapter1.md file file.

chapter1.md used to have a SUMMARY.md title of "How does it Work". Then I renamed the file to how_does_it_work.md.

But it seems like that made the editor extremely confused. It didn't update the SUMMARY.md entry for this page (still referencing chapter1.md) and now every time I click on "How does it Work" (which is supposed to be how_does_it_work.md), it takes forever to load. And also it creates a chapter1.md file again.

I think I fixed this by editing SUMMARY.md manually and changing chapter1.md to how_does_it_work.md.

That said, the original issue about this bug still remains. It's super slow to load the page.

**Comment by nictuku** [comment]
FYI I wasn't using the downloaded Editor, but the online editor.

**Comment by AaronO** [comment]
@nictuku This seems to be caused by a very high server load (seen in our logs), will investigate.

At first I couldn't reproduce the slowness issues you had editing the document itself.

Does it appear when you do specific things or when you edit any part of the document ?

(There are substantial editor improvements coming in the new release: https://beta.gitbook.com)

**Comment by nictuku** [comment]
https://photos.app.goo.gl/2m6YSSIpfvEqQWnq2

It's also slow-ish in the offline app.

4 seconds may not seem much but that sluggishness happens every time I
switch pages.

I'll try the beta too!

**Comment by nictuku** [comment]
Closing this because I've been gotten used to the page load latency.
