### ISSUE TITLE
hide / remove .html for each page

### ISSUE THREAD

**Issue by grand-lotus-iroh** [GitbookIO/feedback#587]
## Category

feature request

## Additional information

would be cool if we could remove / hide the .html extension - if editing htaccess was possible, it would look something like:

```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule ^(.*)\.html$ /$1 [L,R=301] 
```

**Comment by AaronO** [comment]
@grand-lotus-iroh In the next version of `gitbook.com` (https://beta.gitbook.com), this is the default behavior.
