### ISSUE TITLE
Visually disappearing content on Safari

### ISSUE THREAD

**Issue by NocturnalSolutions** [GitbookIO/feedback#604]
## Category

Bug

## What is the current behavior?

In Safari, when scrolling large pages, the text often entirely disappears, showing a large blank area where the content should be. I can regularly reproduce this, but only on fairly long pages where vertical scrolling is required. See the screenshot for an example. You can see by the scrollbar thumb location that I've scrolled to the bottom of a long-ish page, but the content has disappeared.

![gitbook fail](https://user-images.githubusercontent.com/28848562/36041655-751333d0-0d86-11e8-8253-1ed17ff69584.png)

## What is the desired behavior?

The content does not visually disappear after scrolling.

I can accept that this is a Safari bug rather than a Gitbook one, but regardless, this seems to be the only site on the internet where I see this behavior happening, so I'm sure you can find a workaround. :)

## Additional information

Safari 11.0.3 on macOS High Sierra 10.13.3

**Comment by eeeps** [comment]
Duplicate of https://github.com/GitbookIO/gitbook/issues/1530 ?

**Comment by NocturnalSolutions** [comment]
Yes, probably. Self-closing as duplicate.
