### ISSUE TITLE
Github pages support

### ISSUE THREAD

**Issue by tomger** [GitbookIO/feedback#615]
We have a Github Pages, Jekyll & Markdown-based website. The problem is that when GitbookIO pushes a commit to our Github Pages repository Github reports it can't rebuild and publish our site because:
>  Your site is having problems building: Validation failed: User must be a human

We're exploring if we can have a normal Github Pages/Jekyll site and edit the Markdown in the browser using Gitbook.

**Comment by norbertfuhs** [comment]
So basically you want an online editor to edit your Github Pages / Jekyll site right?

**Comment by norbertfuhs** [comment]
Is this issue still open?

**Comment by tomger** [comment]
@norbertfuhs yes, we want an online editor to editor that is compatible with Github pages/Jekyll in general so we're don't get locked in.

**Comment by norbertfuhs** [comment]
Hi @tomger did you also take a look at the [https://www.netlifycms.org/](https://www.netlifycms.org/) ? 

Maybe an alternative if you just need an editor for GitHub pages?

**Comment by tomger** [comment]
@norbertfuhs I took a look at Netlify. That seems like the opposite of what we need, they provide a way to build and deploy your static site in the cloud. Github provides exactly that. We're interested in having a better editor for Jekyll in the cloud while keeping our ability to let Github build and deply it to github.io

I'm going to close to issue as it doesn't sound like this project can help us.
