### ISSUE TITLE
Cannot create new doc from click the link that not exist

### ISSUE THREAD

**Issue by peihsinsu** [GitbookIO/feedback#62]
Before upgrade to 6.0.1... If I add article name and link in the summary.md, after that... I can click the link and will auto create the page file.
But the 6.0.1 will no response when I click the link...
<img width="1038" alt="_2016_7_12_ 11_27" src="https://cloud.githubusercontent.com/assets/1032395/16772887/6589509e-4888-11e6-9811-84e964d3125c.png">

**Comment by SamyPesse** [comment]
It should work as expected.

Can you send me a ZIP of your book at samy[at]gitbook.com. It'll help me reproduce and investigate the issue.

**Comment by peihsinsu** [comment]
Hi Samy

I just sent the archive for you.
As I mentioned in my mail... I'm not sure that I provide the right version for you...@@
There is some version gap...
How can I know the current path of my book? 

Best Wish,
Send by Simon Su

**Comment by SamyPesse** [comment]
It should be fixed in latest release.
