### ISSUE TITLE
Politically incorrect region name "Taiwan, Province of China"

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [GitbookIO/feedback#626]
## Category
GitBook.com / Bug

## What is the current behavior?
1. Sign in
1. Redirected to /account/verify
1. "Taiwan, Province of China" listed in the Country listing (which is inappropriate, wrong and offending in every aspect)

## What is the desired behavior?
"Taiwan" listed in the Country(should be Region to be politically neutral) listing

## Additional information
The region name "Taiwan, Province of China" is politically incorrect and offending to Taiwanese users, please use the neutral name "Taiwan" instead.

If the website rely on the iso-codes package, please use the "common name" field when available instead as with this [patch](https://launchpadlibrarian.net/53161408/use_common_name_instead_when_it_exists.patch) did with the [Ubuntu LoCo Team Portal](http://loco.ubuntu.com/) site.

REF: 

* [Bug #614236 “Wrong Country Name. (Taiwan)” : Bugs : LoCo Team Portal](https://bugs.launchpad.net/loco-team-portal/+bug/614236)
* [Politically incorrect region name "Taiwan, Province of China" · Issue #310 · canonical-websites/snapcraft.io](https://github.com/canonical-websites/snapcraft.io/issues/310)

Thanks in advance!

**Comment by SamyPesse** [comment]
Hi @Lin-Buo-Ren 

We are relying on this module [`phone`](https://github.com/aftership/phone).

We'll look into making this changes as soon as possible.

**Comment by Lin-Buo-Ren** [comment]
Issue forwarded to https://github.com/AfterShip/phone/issues/100

**Comment by Lin-Buo-Ren** [comment]
I'd like to inform you that the upstream has merged a fix.

**Comment by SamyPesse** [comment]
It was already fixed in GitBook.com, we've started using a new module for listing countries.
