### ISSUE TITLE
OSX - VERSION SIX - Raw mode versus document mode - can't switch back and forth

### ISSUE THREAD

**Issue by chrismalek** [GitbookIO/feedback#63]
On 6.0.2 OSX

Note: What I refer to here as "document" mode is the WYSIWYG editor mode. I am not 100% sure if that is what you guys are calling it.

I can't seem to figure out how to move back and forth between "raw" mode and "document" mode. Some of my *.md files are opening in raw mode and some are opening in "document" mode. So gitbook must be saving some state. However, I don't see an option in the menu or toolbar to toggle back and forth.

**Comment by SamyPesse** [comment]
GitBook Editor by default try to open file in "Document" mode, when the file contains HTML or Templating tags, it'll switch to "Raw" mode (WYSIWYG doesn't support Raw HTML and Templating yet).

You can also choose to manually switch to "Raw" mode by using the `aA` button in the toolbar:

<img width="216" alt="screen shot 2016-07-12 at 20 21 36" src="https://cloud.githubusercontent.com/assets/845425/16778427/43a65112-486e-11e6-92d6-8ea79f122e3b.png">

**Comment by chrismalek** [comment]
tricky!!  yes that was it. I had some HTML in the raw text.
