### ISSUE TITLE
Bring Back File Tree

### ISSUE THREAD

**Issue by gszauer** [GitbookIO/feedback#64]
It would be great to have an option to turn the file tree back on like it was in the 5x release. My workflow was pretty dependent on adding files trough that interface. While it's possible to work with the new ux, it slows me down to the point that i just downgraded.

On the topic of the file tree, a "Reveal in Finder" or "Show in Folder" option would be great when right clicking folders or documents.

**Comment by nagim** [comment]
I used that a lot myself, particularly for adding links by drag-and-drop, and while I miss this particular feature, I think the asset manager is better than the file tree. We still have the same right-click context menu for uploading files and folders in the asset manager.

The only thing is that **Import from Computer**, **New File**, **New Folder** buttons should be visible always (they disappear when you start to navigate).

What really should be useful and fast, is if the Editor could notice when files are copied to the repository folders. Then it should be super easy to just copy the files and start working on/with them in the Editor.

**Comment by gszauer** [comment]
@nagim I know it's there, but having to click a button is a pain. I'm constantly adding files, i'd be happy with the asset manager if it was always visible.

**Comment by jrdnhannah** [comment]
Using the 'files' or 'assets' manager was a big part of my workflow, and I don't see myself upgrading to v6 until it's back in a permanent place - having to open a modal every time is going to be a massive pain.

**Comment by SamyPesse** [comment]
Thank you for the feedback.

The goal of the "Files" dialog was to provide a better UX for working with files (preview, more spaces, etc), I'm still trying to understand why the Files Tree is important for you when editing, it seems to me that you should have to use it only a few times for manipulations (create a new folder, upload some files, etc).

We are looking for a solution, we'll maybe add it back

In the mid-time, the last release 6.0.4 includes a keyboard shortcut to open the file dialog.

**Comment by gszauer** [comment]
@SamyPesse I work with a bunch of images. The file tree is helpful, because when i start writing i right click on a folder and upload all my images. But i don't recall the image names off the top of my head. With the tree open, as i'm writing (I write in markup, don't really use the WYSIWYG features for much more than preview) i can just look to see the file names. 

Same thing when i'm using gitbook to write documentation, having a quick glance at a list of .md files i can link to without opening a modal dialog lets me do this much faster.

It would be nice to have an option to hide or show the file tree. I get how it's not useful in everyones workflow, but for me it's a must have.

Thanks for taking the time to reply!

**Comment by SamyPesse** [comment]
The last release `6.1.0` includes a new Files Tree in the sidebar.

Let us now what you think!

PS: @gszauer it also includes an option `Reveal in Finder`.

**Comment by gszauer** [comment]
I love it! Including the file explorer as a tab is great!

**Comment by jrdnhannah** [comment]
Ah brilliant, this release is just what I was looking for. Thanks for the effort guys!

**Comment by nagim** [comment]
Great to see the file tree back! Thanks!
However, it seems that the drag and drop linking should work in raw mode, too (the banner appears at the bottom), but it has no effect. It works in document mode.
Also, Reveal in File Explorer has no effect on Win 7 64bit.
