### ISSUE TITLE
About adding a new chapter

### ISSUE THREAD

**Issue by Fashaun** [GitbookIO/feedback#65]
Hi,  is there any feature in replace of  "Add a new chapter ?" (right click mouse in sidebar)

**Comment by nagim** [comment]
In the newest (6.0.2.) editor, there is an **Add an article** button in the Table of Contents, but right-click and select Add Article also works.

**Comment by Fashaun** [comment]
ok thanks


2016-07-13 13:54 GMT+08:00 nagim <notifications@github.com>:
