### ISSUE TITLE
gitbook build error: getaddrinfo ENOTFOUND cluster.aws.dynobox.co cluster.aws.dynobox.co:80

### ISSUE THREAD

**Issue by linrongbin16** [GitbookIO/feedback#651]
## Category

bug

## What is the current behavior?

My Gitbook(legacy) build error:

https://legacy.gitbook.com/book/linrongbin16/way-to-algorithm/activity

The error message is:

```
getaddrinfo ENOTFOUND cluster.aws.dynobox.co cluster.aws.dynobox.co:80
```

## What is the desired behavior?

build correctly

## Additional information

Gitbook Address:

https://linrongbin16.gitbooks.io/way-to-algorithm/content/

**Comment by AaronO** [comment]
@linrongbin16 This should be resolved, we made some DNS changes on our legacy service today.

**Comment by linrongbin16** [comment]
Great !
