### ISSUE TITLE
Editor 6 OS X - Add a shortcut to show preview, no Syntax highlighting in Markdown

### ISSUE THREAD

**Issue by jk2K** [GitbookIO/feedback#66]
My Version is 6.02, I found some issues

- no shortcut to show preview
- no Syntax highlighting in Markdown
- cursor cannot move when tap to click in OS X

**Comment by SamyPesse** [comment]
`cursor cannot move when tap to click in OS X` -> this one is fixed in the latest release.

I'm working on the other ones

**Comment by jk2K** [comment]
thanks, you hard

**Comment by jk2K** [comment]
I just updated to editor-6.0.3, `cursor cannot move when tap to click in OS X` is not fixed
![demo](https://cloud.githubusercontent.com/assets/4025839/16860599/361b0e02-4a6c-11e6-87d2-a20de6fecb4d.gif)

**Comment by SamyPesse** [comment]
All of these issues should be fixed in latest releases.
