### ISSUE TITLE
Insert link is not work

### ISSUE THREAD

**Issue by RubyXiao** [GitbookIO/feedback#68]
**Command + K** is not working.
I try to use **Markup > Insert link** , after I finish , it is nothing happened.

And where can I open the tool bar? I can't find it now. 

Thanks!

**Comment by SamyPesse** [comment]
**Command + K** is not prompting you to enter a link?

What do you mean by "open the tool bar" ? The toolbar is always displayed.

**Comment by RubyXiao** [comment]
I found this on document mode, sorry.
![picture](https://gitbookio.github.io/blog/assets/2016-01-06-editor-commit.png)

But I can't show preview and use the icon bar.

**Comment by Soreine** [comment]
@RubyXiao are you using  the latest version of the Editor (6.0.3) ? It looks like you are not, from the screenshot you sent.

Do you mean that you would like to be able to use the formatting toolbar while in raw mode ?

**Comment by RubyXiao** [comment]
I used version 6.0.2 yesterday.
I already updated to 6.0.3 today, insert link is working in document mode,
But it still can't use in the preview mode.

> Do you mean that you would like to be able to use the formatting toolbar while in preview mode ?
Yes, you're right.

**Comment by speedornothing** [comment]
I think that writing or editing a link using markdown syntax is more easier and more efficient.
At least, the editor should be able to identify the link syntax. If not, it will no longer be a **markdown editor**,

**Comment by Soreine** [comment]
I close this issue in favor of two separate ones
@RubyXiao  https://github.com/GitbookIO/feedback/issues/98
@speedornothing https://github.com/GitbookIO/feedback/issues/97
