### ISSUE TITLE
Editor 6 OS X — Editing Files

### ISSUE THREAD

**Issue by manngo** [GitbookIO/feedback#69]
I cannot select a place in the code by clicking. I can only do so by click at the very beginning of the file and using the arrow keys.

**Comment by drreen** [comment]
Having same issues

**Comment by AaronO** [comment]
@manngo @drreen Can you guys elaborate here ?

Clicking anywhere in a code block or the source file works for me as expected.

Can you specify what's the expected behavior and what's currently not happening as expected ?

**Comment by drreen** [comment]
Examples in raw mode:

- In raw mode when whole text is highlighted, clicking anywhere into the editor won't remove the highlighting:
http://recordit.co/UcMibyM8W8 (on every mouse stop I am actually clicking)

- double click on a word to highlight -> cursor remains in old position

- clicking into an empty line -> cursor remains in old position
http://screencast.com/t/Q7WQRfo6

**Comment by drreen** [comment]
Another one:
http://screencast.com/t/KaFSV3D3hj

**Comment by SamyPesse** [comment]
We've just fixed the selection/cursor issue 👷 , it'll be in today release.

**Comment by SamyPesse** [comment]
Fixed in 6.0.3
