### ISSUE TITLE
Editor 6 OS X — Tab Key

### ISSUE THREAD

**Issue by manngo** [GitbookIO/feedback#71]
Please allow the option to insert `tab` instead of spaces. This is especially useful when including code samples and editing CSS Files.

**Comment by drreen** [comment]
+1

**Comment by SamyPesse** [comment]
In raw mode or document mode, currently:

- **In raw mode**: we include 2 spaces when pressing Tab (I can change it to detect indentation)
- **In document mode**: we detect indentation when pressing Tab in a code block (we default to 4 spaces).

I'll add a configuration for default indentation when pressing tab in a code block.

**Comment by SamyPesse** [comment]
Fixed in 6.0.3
