### ISSUE TITLE
Editor 6 OS X —  issue working on tables

### ISSUE THREAD

**Issue by drreen** [GitbookIO/feedback#73]
- Copy from within the editor and paste it into a table cell is not working
- Highlighting text in a table cell works, but the highlighted text cannot be deleted, cut ot 

Also when clicking on an empty bullet point which is located right before a table, the cursor jumps to the first th instead

**Comment by Soreine** [comment]
Concerning the bullet point, you might have inserted the table inside the bullet point by inadvertence.

**Comment by drreen** [comment]
Tables seem to be rendered not correctly, see video:
http://screencast.com/t/yXxRuDLxH
(bug happens 0:14)

**Comment by SamyPesse** [comment]
@drreen I'm working on fixing it for next release 👷

**Comment by AaronO** [comment]
@drreen Just landed a fix for table previews (when in raw mode) in the master. Will likely get released tomorrow
