### ISSUE TITLE
Editor 6 OS X — Table Headers Not Working

### ISSUE THREAD

**Issue by manngo** [GitbookIO/feedback#78]
If I create a table in either of the following formats:

	[cols="2*", options="header"]
	|===
	|Name of Column 1
	|Name of Column 2
	
	|Cell in column 1, row 1
	|Cell in column 2, row 1
	
	|Cell in column 1, row 2
	|Cell in column 2, row 2
	|===
	
	|===
	|Name of Column 1 |Name of Column 2
	
	|Cell in column 1, row 1
	|Cell in column 2, row 1
	
	|Cell in column 1, row 2
	|Cell in column 2, row 2
	
	|===

(from the asciidoctor documentation), the table header is incorrectly drawn:

![tables](https://cloud.githubusercontent.com/assets/3796633/16827450/16ca830e-49ca-11e6-96b9-514f19dd7bef.png)

**Comment by SamyPesse** [comment]
Same as #80, it'll be fixed in the upcoming release.
