### ISSUE TITLE
Editor 6 OS X — Inserting Images

### ISSUE THREAD

**Issue by manngo** [GitbookIO/feedback#79]
I cannot insert images using the menu item `Markup|Insert Image…`.

If I choose a file from the computer, it accepts it, but only adds it to the library, and places it into a folder I hadn’t seen before, `assets`. I then need to type the image location myself.

- Where is the library located?
- Is the assets folder real? Is it new?

Thanks

**Comment by SamyPesse** [comment]
In document mode, when inserting an image, it upload it to an `assets` folder (in your book) then insert it in the page.
In the raw mode, you need to write the markup for the image manually.

Are you using the document mode or the raw mode?

**Comment by manngo** [comment]
I guess I must be in raw mode. How do I change to document mode?

Thanks

Mark

On 14/07/2016 7:47 pm, Samy Pessé wrote:
>
> In document mode, when inserting an image, it upload it to an |assets| 
> folder (in your book) then insert it in the page.
> In the raw mode, you need to write the markup for the image manually.
>
> Are you using the document mode or the raw mode?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/GitbookIO/feedback/issues/79#issuecomment-232618913>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ADnumUuPEz93yLvgfW0gHKOOAAnbPAWIks5qVgXNgaJpZM4JMD2W>.
>


-- 


  Mark Simon

Manngo Net Pty Ltd

mobile:0411 246 672

email:mark@manngo.net <mailto:mark@comparity.net>
web:http://www.manngo.net

Resume:http://mark.manngo.net

**Comment by SamyPesse** [comment]
The raw mode (with the editor and preview side by side) is displayed automatically when the file contains HTML or Templating tags, do you use any of them?

Otherwise, there is a button `aA` can be used to switch to document mode.

**Comment by SamyPesse** [comment]
The `aA` button is a switch for document/raw modes.

### Document mode:

![screen shot 2016-07-14 at 12 34 57](https://cloud.githubusercontent.com/assets/845425/16836762/7660a704-49bf-11e6-8a9c-fdb19b51129c.png)

### Raw mode

![screen shot 2016-07-14 at 12 34 53](https://cloud.githubusercontent.com/assets/845425/16836763/76824dfa-49bf-11e6-92eb-49b8a8fe81af.png)


Which one are you using?

**Comment by manngo** [comment]
That’s the button I tried, but it doesn’t seem to do anything at all. 
Certainly it doesn’t switch modes for me.


I also notice that on your screen shot the Last Edited bar includes a 
couple of icons on the right. Mine doesn’t.

Here is a screen shot:

Thanks

Mark

On 14/07/2016 8:36 pm, Samy Pessé wrote:
>
> The |aA| button is a switch for document/raw modes.
>
>
>       Document mode:
>
> screen shot 2016-07-14 at 12 34 57 
> <https://cloud.githubusercontent.com/assets/845425/16836762/7660a704-49bf-11e6-8a9c-fdb19b51129c.png>
>
>
>       Raw mode
>
> screen shot 2016-07-14 at 12 34 53 
> <https://cloud.githubusercontent.com/assets/845425/16836763/76824dfa-49bf-11e6-92eb-49b8a8fe81af.png>
>
> Which one are you using?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub 
> <https://github.com/GitbookIO/feedback/issues/79#issuecomment-232628547>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/ADnumSb_YXdHmPf5lY30HZMP6LXZMDKFks5qVhETgaJpZM4JMD2W>.
>


-- 


  Mark Simon

Manngo Net Pty Ltd

mobile:0411 246 672

email:mark@manngo.net <mailto:mark@comparity.net>
web:http://www.manngo.net

Resume:http://mark.manngo.net

**Comment by SamyPesse** [comment]
The button not present in raw mode is related to #98

You cannot switch to document mode if it contains HTML/Templating tags (#12).
