### ISSUE TITLE
Gitbook Editor 6.0.3 review 

### ISSUE THREAD

**Issue by KINGSABRI** [GitbookIO/feedback#82]
Hi @all

First, contrgrats for the complete new shape shifting and fixing long list of bugs. As I said before, when you don't show updates for a long time that means you're working on something big.

### System Information

* Ubuntu 16.4 TLS
* Gitbook desktop editor 6.0.3 
* Create a new book \(local repository only\)

Here the list of issues I've noticed

#### Creating sub-chapter disappeared

* I can't create sub-chapter anymore, even creating a new-chapter doesn't get reflected in SUMMRY. MD **[FIXED]**
* Creating a new chapter doesn't create a new file, but chapter keeps existing after closing gitbook editor  **[FIXED]**
* File and folder tree in the sidebar disappeared  **[FIXED]**

#### Create a new File, Folder and Summary  
Nothing gets created on the local disk  **[FIXED]**

#### Spellchecking & Proofreading
Spellchecking & Proofreading are not working, both are enabled

#### Can't find files 
I can't see 
- book.json 
- Imported images  **[FIXED]**
  - when I import and image it says it's in `/assets/cluster9.png`. Whoever there is not folder created 

Note, on the top bar, File button shows all created files, folders, /assets/images but nothing on the local disk 

When I open Rubyfu book (written via older versions) the sub-chapters appear but I don't check anything out to avoid damaging the project structure.

Thanks!

**Comment by mobi3006** [comment]
I am really disappointed about the 6.0.4 on my windows 7 machine. 5.x was really good

* I am missing the filetree - I need it to set links and I do not want to expand the Chaptertree to find the page I want to edit. It would be even better to have a filetree and incremetal search when typing to find and select the file without touching the mouse ... @SamyPesse: developers like this much more 
* every Save results in a commit
* Ctrl-F does not work

I have to reinstall 5.x - this is not the way I want to work .... is it still available for download?

**Comment by SamyPesse** [comment]
@mobi3006 Are you using the raw mode (editing markdown) or document mode (WYSIWYG)?

1. In the document mode, including a link is easier than before, just press `Ctrl+K` then it'll autocomplete your link:

   ![link](https://cloud.githubusercontent.com/assets/845425/16889852/cb12149c-4ae9-11e6-9a8c-c4f2d115274c.gif)

   We'll probably add back the files tree for authors using the raw mode.

2. The save button has been improved, you can change file without saving then save after editing multiple file (to create a commit containing multiple changes). In the settings you can also select the option to be prompt for "Commit message".


We are working hard on improving this version, and I'm convinced that overall the UX and the result will be much better than 5.x.
The issue right now is that "Raw" mode doesn't support HTML and Templating tags, and the Raw mode is not as good as the "Document" mode or the old editor, so most authors having HTML/Templating tags are complaining about this version.

**Comment by mobi3006** [comment]
Hi Samy, thx for your fast reply ... is it possible to chat here:
https://gitbook-community.slack.com/messages/general/

Bye,
Pierre

2016-07-16 0:12 GMT+02:00 Samy Pessé <notifications@github.com>:

**Comment by mobi3006** [comment]
can I download and install the old version 5.x? where to download from?

I edited the book.json and deleted the complete content ... I saved ... now
when starting the GitBookEditor I get a red ERROR MESSAGE and the
Chaptertree never loads ...

sorry, I was that much happy with the old version ...

2016-07-16 0:21 GMT+02:00 Pierre Feldbusch <mobi3006@googlemail.com>:

**Comment by KINGSABRI** [comment]
Hi @SamyPesse 
Thanks for bringing the file tree back 

The existing of creating a new file, folder, image, chapter etc. is remaining. Even when I try to see what git see 

```
 KING  Archer  test1  master  $  git status 
On branch master
Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        deleted:    Claw_Marks.png
        modified:   SUMMARY.md
        deleted:    chapter01/README.md
        new file:   chapter1.md

```


Notice the deleted file/folders? I just added them then save.

**Comment by Soreine** [comment]
@KINGSABRI 
The Editor works on the local git repository, but does not update the filesystem accordingly (since it does not use it). That's something we will fix soon enough, but it is likely to be one-way at first. The other way is tricky: to handle updates to the filesystem so they reflect in the Editor.

**Comment by KINGSABRI** [comment]
@Soreine Thanks for clarification, actually I'm still worried about using the new version for my book. For now I'm using Atom until these issues get fixed. 

I hope these issues get fixed as soon as possible, I know you're working so hard guys and you're doing a great job. But some issues could miss the whole things. 

God bless you guys

**Comment by SamyPesse** [comment]
@KINGSABRI In the latest release the sync with files on disk is done.

The other side synchronisation is on our roadmap (#101).

**Comment by KINGSABRI** [comment]
@SamyPesse Thanks man

I update the list of issues with  **[FIXED]** tage to confirm the fixes 

You guys are awesome

**Comment by Soreine** [comment]
Thank you @KINGSABRI
I close this thread. I opened a separate issue for the proofreading issue https://github.com/GitbookIO/feedback/issues/193
