### ISSUE TITLE
Editor 6 OS X — Does not paste empty lines

### ISSUE THREAD

**Issue by manngo** [GitbookIO/feedback#83]
I don’t know whether this is a separate issue from the one about pasting from the terminal, so here it is.

Editor will not past any empty lines, either from an external editor or from another Editor file.

I have tried changing the line ending on the external editor to CRLF, but that doesn’t make any difference at all.

It will work, however, when copying and pasting within the _same_ document.

**Comment by manngo** [comment]
Additional information: I normally paste using Cmd-V. I have found that it works correctly if I right-click instead … ?

**Comment by Soreine** [comment]
I close this in favor of #155
