### ISSUE TITLE
Editor 6.0.4 - syntax highlight in asciidoc

### ISSUE THREAD

**Issue by nagim** [GitbookIO/feedback#87]
Hi,

Glad that syntax highlighting in raw mode returns, however, in asciidoc, very few elements gets highlighted (namely: headers and a few list types), none of the inline formatting (bold, etc.), links, blocks, bullet and numbered lists, etc.

ToC rendering is still off (see #47 ).

**Comment by KINGSABRI** [comment]
Syntax highlight still not working

**Comment by SamyPesse** [comment]
It should be improved (performance and pertinence) in `6.1.1`.

**Comment by nagim** [comment]
Thanks @SamyPesse it looks so much better now.
Couple of ideas for enhancement:
- List characters (bullets, numbers) could be stronger, more noticeable
- Text between backticks and the `#` of the custom tags (`[tag]#text#`), after `link:` and `image:` macro (the URL and image path), source code could use different color
- Simple highilighting (#text#) doesn't work in the preview

Thanks a lot!
