### ISSUE TITLE
New editor issues

### ISSUE THREAD

**Issue by Jun90925** [GitbookIO/feedback#93]
I don't like the new ediot in new version 6.0.
I want to write article by my own feagure, but actually I can't.
Such as inserting a link, I can't type like '[xxx](xxx.md)' to do it, but I must use ctrl + k to insert it.
When I want to open the link, it open my windows file system (old version will open the linked .md file).

I hope that the new version will be able to provide options to switch to the new editor and the old editor.

And every time I save some changes on gitbook, I can't find the changes in the file system. Just don't know why. Is there any solution to this?

Thanks for the hard work on Gitbook !

**Comment by SamyPesse** [comment]
The popover issue is fixed in version `6.1.0`.
