### ISSUE TITLE
Cannot read property 'getFullName' of null

### ISSUE THREAD

**Issue by longxianlin** [GitbookIO/feedback#96]
after update, have this error when sync....

because  gitbook move my local git repository books to somewhere and have this error.

how to fixed?
1, remove this book.
2, git clone book from repo.  
3, import again...

**Comment by Soreine** [comment]
@longxianlin Do you still have a copy of your local repository that triggers this error?
If so, you can you send me a zip of your book by email at `nicolas[at]gitbook.com` ?

**Comment by changkun** [comment]
I have the same problem. However I can't remove this book from my computer since I have change to start a pull request.

**Comment by govvin** [comment]
I'm trying to create a new changeset and I get the same error, using GitBook 7.012 on Xubuntu:

![image](https://cloud.githubusercontent.com/assets/5821688/26525080/6a9d30ae-437e-11e7-87c0-5b661c9005dd.png)

**Comment by dartajax** [comment]
I am receiving a similar error message. Using the GitBook Editor on my computer is causing me to lose many changes.

Any ideas how to resolve a situation like this one pasted below? The `Create a change request` was an effort to resolve the "Failed to inflate loose object" issue with many changes made locally on the GitBook Editor not being synced up to the web version.

![image](https://cloud.githubusercontent.com/assets/7493331/26694109/3f6b6b40-46bb-11e7-8d6f-df6fb0ad9e00.png)

**Comment by codesmythe** [comment]
I am also having the same issue.

**Comment by DanielWright** [comment]
I'm also having this issue. Please let me know what kind of diagnostic info I can provide.

**Comment by vejuhust** [comment]
I'm also having this issue whiling creating new change request.

**Comment by jamesking** [comment]
Me too
