### ISSUE TITLE
Editor 6.1.0 - File tree

### ISSUE THREAD

**Issue by nagim** [GitbookIO/feedback#99]
Hi!

Great to see the file tree back! Thanks!

However, the drag and drop linking does not work in raw mode, too (the banner appears at the bottom, but it has no effect). It works in document mode.

Also, Reveal in File Explorer has no effect on Win 7 64bit.

Thanks for all the hard work!

**Comment by KINGSABRI** [comment]
Ok, when you create a new file/folder, can you see that file/folder on the disk from your file manager?

**Comment by nagim** [comment]
After Save&Sync, I can see (but if I only Save, it's not yet visible).

**Comment by SamyPesse** [comment]
@nagim @KINGSABRI This issue of file not shown on the disk will be fixed in next release.

I'm closing this issue since the drag and drop is the related to the behaviour of the markup toolbar (#98).

**Comment by nagim** [comment]
Reveal in File Explorer is still not working.

**Comment by SamyPesse** [comment]
@nagim we are using `shell. showItemInFolder ` from electron, maybe it's related to https://github.com/electron/electron/issues/4349 or related to https://github.com/electron/electron/issues/6514

I'll investigate.

**Comment by nagim** [comment]
Great, thanks!
